const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '../public/index.html'), 'utf8');

assert.match(html, /\.tms-stats-row\s*\{/, 'court page should define scoped tms stats styles');
assert.match(html, /\.tms-table-card\s*\{/, 'court page should define scoped tms table card styles');
assert.match(html, /\.tms-mini-bar\s*\{/, 'court page should define scoped tms mini bar styles');
assert.match(html, /\.tms-record-add-box\s*\{/, 'court page should define scoped modal form layout styles');
assert.match(html, /\.tms-toolbar\s*\{/, 'court page should define scoped toolbar styles');
assert.match(html, /\.tms-pagination\s*\{/, 'court page should define scoped pagination styles');
assert.match(html, /<div class="tms-stats-row" id="courtStatsRow"><\/div>/, 'court page should use the upgraded tms stats row container');
assert.match(html, /<div class="tms-table-card">[\s\S]*<div class="tms-table-wrapper">[\s\S]*<table class="tms-table">/, 'court page should use the upgraded tms table wrapper');
assert.match(html, /<th>下次跟进日期<\/th>/, 'court table should show next follow-up date');
assert.match(html, /id="courtAccountTypeFilter"/, 'court toolbar should provide account type filter');
assert.match(html, /id="courtOwnerFilter"/, 'court toolbar should provide owner filter');
assert.match(html, /id="courtMoreActions"/, 'court toolbar should provide more actions menu');
assert.match(html, /导入CSV[\s\S]*财务迁移预览[\s\S]*备份/, 'court more actions should include import, finance migration preview, and backup');
assert.doesNotMatch(html, /courtMoreActionValue_dropdown[\s\S]*class="tms-dropdown-item[^"]*">更多操作</, 'court more actions menu should not include a redundant self option');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('validUntil'\)"[\s\S]*?>会员到期/, 'court table should keep expiry sorting');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('balance'\)"[\s\S]*?>当前余额/, 'court table should keep balance sorting');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('spentAmount'\)"[\s\S]*?>消费金额/, 'court table should keep spending sorting');
assert.match(html, /<th class="tms-sticky-r"[\s\S]*操作/, 'court table should freeze the action header');
assert.match(html, /查看[\s\S]*编辑[\s\S]*订场/, 'court row actions should use shorter copy');
assert.doesNotMatch(html, /courtCampusFilterBtn|courtCampusFilterMenu/, 'court table should no longer expose campus header filter');
assert.match(html, /id="courtPageSize"/, 'court table should support page size selection');
assert.match(html, /20条\/页[\s\S]*50条\/页[\s\S]*100条\/页/, 'court page size selector should offer 20, 50, and 100 rows per page');
assert.match(html, /function openCourtFinanceModal\(/, 'court page should expose a dedicated finance modal');
assert.match(html, /记一笔流水/, 'court page should expose the standalone finance entry label');
assert.match(html, /function openCourtModal[\s\S]*最近跟进日期[\s\S]*下次跟进日期/, 'court edit modal should keep follow-up fields');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*充值\/消费记录[\s\S]*add-rec-row/, 'court edit modal should no longer contain the inline finance entry area');
assert.match(html, /function renderCourtMiniBar\(/, 'court page should expose a dedicated mini bar renderer');
assert.match(html, /class="tms-sticky-l"/, 'court page should freeze the left name column');
assert.match(html, /class="tms-sticky-r"/, 'court page should freeze the right action column');
assert.match(html, /class="tms-action-link"/, 'court page should render action links with the scoped visual style');
assert.match(html, /function openCourtModal[\s\S]*tms-section-header[\s\S]*tms-form-row/, 'court edit modal should use the upgraded local form layout');
assert.match(html, /function openCourtFinanceModal[\s\S]*tms-record-add-box/, 'court finance modal should use the upgraded local record card layout');
assert.match(html, /function openCourtFinanceModal[\s\S]*历史记录[\s\S]*tms-history-list/, 'court finance modal should keep the Gemini-style history list under the entry form');
assert.match(html, /function getCourtDuplicateCandidates\(/, 'court save flow should detect duplicates');
assert.match(html, /发现可能重复的订场用户：/, 'court save flow should warn about possible duplicates');
assert.match(html, /手机号优先，若无手机号则按姓名\+校区/, 'court duplicate reminder should prioritize phone and then name plus campus');
assert.match(html, /search.*nextFollowUp|nextFollowUp.*search|courtSearch[\s\S]*followUp/, 'court search should cover follow-up fields');
assert.match(html, /courtPageSize=\d+/, 'court page should keep its own page size state');
assert.match(html, /function setCourtPageSize\(/, 'court page should expose page size switching');
assert.match(html, /function handleCourtMoreAction\(/, 'court page should expose more action handler');
assert.match(html, /id="courtBatchDelBtn"[^>]*style="display:none"/, 'court batch delete button should stay hidden before any selection');
assert.match(html, /function updateCourtBatchButton\([\s\S]*btn\.style\.display=selectedCourtIds\.size\?'inline-flex':'none'/, 'court batch delete button should only show when rows are selected');

console.log('court page view tests passed');
