const assert = require('assert');
const { appSource: html } = require('./helpers/read-index-bundle');

assert.match(html, /<div class="sb-sec">教学管理<\/div>/, 'sidebar should group teaching pages');
assert.match(html, /<div class="sb-sec">课程管理<\/div>/, 'sidebar should group course pages');
assert.match(html, /<div class="sb-sec">场地与资源<\/div>/, 'sidebar should group resource pages');

assert.match(html, /goPage\('products',this\)[\s\S]*?课程产品/, 'sidebar should keep products page');
assert.match(html, /goPage\('packages',this\)[\s\S]*?售卖课包/, 'sidebar should add packages page');
assert.match(html, /goPage\('purchases',this\)[\s\S]*?购买记录/, 'sidebar should add purchases page');
assert.match(html, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should add account management page');
assert.doesNotMatch(html, /goPage\('entitlements',this\)[\s\S]*?权益账户/, 'sidebar should hide the old entitlement page entry');

assert.match(html, /id="page-packages"/, 'should have packages page section');
assert.match(html, /id="page-purchases"/, 'should have purchases page section');
assert.match(html, /course-showcase/, 'course product page should use the new showcase container');
assert.match(html, /course-package-showcase/, 'package page should use the new showcase container');
assert.match(html, /product-card-shell/, 'product page should render the gemini-style product cards');
assert.match(html, /package-card-shell/, 'package page should render the gemini-style package cards');
assert.match(html, /归属教练[\s\S]*购买时选择[\s\S]*可上课教练/, 'package card should distinguish sale owner coach from teachable coaches');
assert.match(html, /主归属教练[\s\S]*可上课教练/, 'purchase records should expose owner coach and teachable coaches');
assert.doesNotMatch(html, /tms-pill-tabs/, 'sidebar navigation should replace the demo top tabs');
assert.doesNotMatch(html, /const t=\{students:[\s\S]*?\n\s*const t=\{students:/, 'page title map should not be declared twice after merge');
assert.match(html, /workbench:'工作台'/, 'page title map should include coach workbench');
assert.match(html, /function syncPackageProductMeta/, 'package modal should sync product metadata');
assert.match(html, /课程类型跟随课程产品/, 'package modal should explain course type follows product');
assert.match(html, /归属教练不在这里维护，实际售卖时按购买记录选择/, 'package modal should explain owner coach is selected at purchase time');
assert.match(html, /function productHasReferences/, 'product modal should know whether product is referenced');
assert.match(html, /function packageHasPurchases/, 'package modal should know whether package is sold');
assert.match(html, /核心字段已锁定/, 'locked core fields should show operator-facing hint');
assert.match(html, /function openPurchaseDetailModal/, 'purchase page should have detail modal');
assert.match(html, /function openPurchaseEditModal/, 'purchase page should have edit modal');
assert.match(html, /function savePurchaseEdit/, 'purchase page should save purchase edits');
assert.match(html, /function openPurchaseModal/, 'purchase page should provide the unified purchase modal');
assert.match(html, /function openPurchaseModal[\s\S]*renderCourtDropdownHtml\('pur_studentId','选择学员'/, 'purchase modal should pick the student in the same step');
assert.match(html, /function openPurchaseModal[\s\S]*支付方式[\s\S]*margin-bottom:0[\s\S]*可上课教练/, 'purchase modal should put pay method and allowed coach fields on separate rows to avoid layout overlap');
assert.match(html, /＋ 课包购买/, 'purchase page should expose a direct package purchase entry button');
assert.match(html, /<th style="width:120px;padding-left:20px">购买日期<\/th><th style="width:140px">学员<\/th><th style="width:170px">售卖课包<\/th><th style="width:120px">主归属教练<\/th>/, 'purchase table should show owner coach directly in the list');
assert.doesNotMatch(html, /先选择学员[\s\S]*下一步/, 'purchase modal should not require a separate first-step student gate');
assert.match(html, /购买时规则快照/, 'purchase detail should show package snapshot');
assert.match(html, /支付日期[\s\S]*系统录入时间/, 'purchase detail should show business date and system recorded time');
assert.match(html, /function openPurchaseVoidModal/, 'purchase page should use dedicated void modal');
assert.match(html, /function voidPurchase/, 'purchase page should send void reason');
assert.match(html, /作废原因/, 'void modal should require reason');
assert.match(html, /function resolveUniqueStudentIdByText/, 'purchase import should resolve students uniquely');
assert.match(html, /function resolveUniquePackageIdByText/, 'purchase import should resolve packages uniquely');
assert.match(html, /匹配到多个/, 'purchase import should warn duplicate matches');
assert.match(html, /固定使用结束日优先/, 'package modal should explain usage end date priority');
assert.match(html, /真正消课的是课包余额/, 'purchase page should explain package balance purpose');
assert.match(html, /私教课/, 'course pages should expose 私教课 as a fixed type');
assert.match(html, /体验课/, 'course pages should expose 体验课 as a fixed type');
assert.match(html, /训练营/, 'course pages should expose 训练营 as a fixed type');
assert.match(html, /大师课/, 'course pages should expose 大师课 as a fixed type');
assert.doesNotMatch(html, /课程性质/, 'course pages should not mention the removed 课程性质 field');
assert.doesNotMatch(html, /正式课/, 'course pages should not keep the old 正式课 wording');

console.log('course management nav tests passed');
