const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');

const pagesCss = fs.readFileSync(path.join(__dirname, '../public/assets/styles/pages.css'), 'utf8');
function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(fnBody('toggleCourtDropdown'), /const container=dropdown\.closest\('\.mbody'\)/, 'dropdown opening direction should account for modal body clipping');
assert.match(fnBody('toggleCourtDropdown'), /containerRect\.bottom/, 'dropdown should compare available space against the modal scroll body');
assert.match(fnBody('toggleCourtDropdown'), /spaceBelow<menuHeight\+12&&spaceAbove>spaceBelow/, 'dropdown should open upward when modal space below is too small');
assert.match(pagesCss, /\.tms-stats-row\s*\{/, 'court page should define scoped tms stats styles');
assert.match(pagesCss, /\.tms-table-card\s*\{/, 'court page should define scoped tms table card styles');
assert.match(pagesCss, /\.tms-mini-bar\s*\{/, 'court page should define scoped tms mini bar styles');
assert.match(pagesCss, /\.tms-record-add-box\s*\{/, 'court page should define scoped modal form layout styles');
assert.match(pagesCss, /\.tms-toolbar\s*\{/, 'court page should define scoped toolbar styles');
assert.match(pagesCss, /\.tms-pagination\s*\{/, 'court page should define scoped pagination styles');
assert.match(html, /<div class="tms-stats-row" id="courtStatsRow"><\/div>/, 'court page should use the upgraded tms stats row container');
assert.match(html, /<div class="tms-table-card">[\s\S]*<div class="tms-table-wrapper">[\s\S]*<table class="tms-table">/, 'court page should use the upgraded tms table wrapper');
assert.match(html, /<th>末次跟进日期<\/th>[\s\S]*<th>下次跟进日期<\/th>/, 'court table should show last and next follow-up dates');
assert.match(html, /id="courtAccountTypeFilter"/, 'court toolbar should provide account type filter');
assert.match(html, /id="courtOwnerFilter"/, 'court toolbar should provide owner filter');
assert.match(html, /id="courtMoreActions"/, 'court toolbar should provide more actions menu');
assert.match(html, /批量选择[\s\S]*导入CSV[\s\S]*财务迁移预览[\s\S]*备份/, 'court more actions should include batch select, import, finance migration preview, and backup');
assert.doesNotMatch(html, /courtMoreActionValue_dropdown[\s\S]*class="tms-dropdown-item[^"]*">更多操作</, 'court more actions menu should not include a redundant self option');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('validUntil'\)"[\s\S]*?>会员到期/, 'court table should keep expiry sorting');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('recentFollowUpDate'\)"[\s\S]*?>末次跟进日期/, 'court table should support sorting by recent follow-up date');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('nextFollowUpDate'\)"[\s\S]*?>下次跟进日期/, 'court table should support sorting by next follow-up date');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('balance'\)"[\s\S]*?>当前余额/, 'court table should keep balance sorting');
assert.match(html, /<th class="tms-sortable" onclick="setCourtSort\('spentAmount'\)"[\s\S]*?>消费金额/, 'court table should keep spending sorting');
assert.match(fnBody('setCourtSort'), /courtSortKey='';courtSortDir='desc'/, 'court sorting should cycle back to no sort');
assert.match(pagesCss, /\.tms-sort-icon[^}]*display:inline-flex[^}]*align-items:center[^}]*justify-content:center/s, 'sort icon should align vertically with header text');
assert.match(pagesCss, /\.tms-sort-icon svg[^}]*width:16px[^}]*height:16px/s, 'sort icon should use the larger mac-style svg glyph');
assert.match(html, /<th class="tms-sticky-r"[\s\S]*操作/, 'court table should freeze the action header');
assert.match(html, /查看[\s\S]*编辑[\s\S]*订场/, 'court row actions should use shorter copy');
assert.doesNotMatch(html, /courtCampusFilterBtn|courtCampusFilterMenu/, 'court table should no longer expose campus header filter');
assert.match(html, /id="courtPageSize"/, 'court table should support page size selection');
assert.match(html, /20条\/页[\s\S]*50条\/页[\s\S]*100条\/页/, 'court page size selector should offer 20, 50, and 100 rows per page');
assert.match(html, /function openCourtFinanceModal\(/, 'court page should expose a dedicated finance modal');
assert.match(html, /记一笔流水/, 'court page should expose the standalone finance entry label');
assert.doesNotMatch(html, /<th[^>]*>充值\/消费记录<\/th>/, 'court table should not keep a separate finance history column');
assert.doesNotMatch(fnBody('renderCourts'), /openCourtHist\('\$\{u\.id\}'\)/, 'court rows should not open finance history from a separate list column');
assert.match(html, /function openCourtModal[\s\S]*末次跟进日期[\s\S]*下次跟进日期/, 'court edit modal should keep follow-up fields');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*充值\/消费记录[\s\S]*add-rec-row/, 'court edit modal should no longer contain the inline finance entry area');
assert.match(html, /function renderCourtMiniBar\(/, 'court page should expose a dedicated mini bar renderer');
assert.match(html, /class="tms-sticky-l"/, 'court page should freeze the left name column');
assert.match(html, /class="tms-sticky-r"/, 'court page should freeze the right action column');
assert.match(pagesCss, /#page-courts \.tms-table th\.tms-sticky-l\s*\{[^}]*top:0[^}]*left:0[^}]*z-index:140/s, 'court left header should stay fixed on both horizontal and vertical scroll');
assert.match(pagesCss, /#page-courts \.tms-table th\.tms-sticky-r\s*\{[^}]*top:0[^}]*right:0[^}]*z-index:140/s, 'court right header should stay fixed on both horizontal and vertical scroll');
assert.match(pagesCss, /#page-courts \.tms-table th\s*\{[^}]*background-color:#FDF7F2/s, 'court sticky and normal headers should share the same background');
assert.match(pagesCss, /#page-courts \.tms-table tbody tr:hover td\.tms-sticky-l[\s\S]*#page-courts \.tms-table tbody tr:hover td\.tms-sticky-r/s, 'court sticky columns should join whole-row hover');
assert.match(html, /class="tms-action-link"/, 'court page should render action links with the scoped visual style');
assert.match(html, /function openCourtModal[\s\S]*tms-section-header[\s\S]*tms-form-row/, 'court edit modal should use the upgraded local form layout');
assert.match(pagesCss, /\.modal\.modal-court \.tms-form-control[^}]*height:38px[^}]*font-size:13px[^}]*font-weight:400/s, 'court modal inputs should use 38px height with normal 13px text');
assert.match(pagesCss, /\.modal\.modal-court \.tms-form-label[^}]*font-size:11px[^}]*font-weight:400/s, 'court modal labels should use normal 11px text');
assert.match(pagesCss, /\.modal\.modal-court \.tms-checkbox-matrix[^}]*font-size:10px/s, 'court linked student selector should use 10px student text');
assert.match(html, /tms-form-row court-date-row[\s\S]*f_campus[\s\S]*f_joinDate[\s\S]*f_recentFollowUpDate[\s\S]*f_nextFollowUpDate/, 'court modal should place campus and three date fields in one row');
assert.match(fnBody('openCourtModal'), /renderCourtDropdownHtml\('f_campus','校区',\[\{value:'',label:'-'\},\.\.\.campusList\],rv\(r,'campus'\),true\)/, 'court modal should allow blank campus');
assert.match(fnBody('openCourtModal'), /courtDateButtonHtml\('f_joinDate',rv\(r,'joinDate'\)\)/, 'court modal should allow blank join date');
assert.match(html, /function openCourtFinanceModal[\s\S]*tms-record-add-box/, 'court finance modal should use the upgraded local record card layout');
assert.match(html, /function openCourtFinanceModal[\s\S]*历史记录[\s\S]*tms-history-list/, 'court finance modal should keep the Gemini-style history list under the entry form');
assert.match(pagesCss, /\.modal\.modal-court \.tms-record-add-box \.tms-dropdown-display[^}]*font-size:12px/s, 'court finance entry row should use smaller dropdown text to avoid overlapping');
assert.match(html, /function openCourtFinanceModal[\s\S]*flex:0 0 96px[\s\S]*renderCourtDropdownHtml\('nrType','类型'[\s\S]*flex:0 0 96px[\s\S]*renderCourtDropdownHtml\('nrCategory','项目'[\s\S]*flex:0 0 118px[\s\S]*renderCourtDropdownHtml\('nrPayMethod','支付'/s, 'court finance modal should narrow the first three selectors to avoid stacking');
assert.match(html, /function getCourtDuplicateCandidates\(/, 'court save flow should detect duplicates');
assert.match(html, /发现可能重复的订场用户：/, 'court save flow should warn about possible duplicates');
assert.match(html, /手机号优先，若无手机号则按姓名\+校区/, 'court duplicate reminder should prioritize phone and then name plus campus');
assert.match(html, /search.*nextFollowUp|nextFollowUp.*search|courtSearch[\s\S]*followUp/, 'court search should cover follow-up fields');
assert.match(html, /id="courtSearch"[^>]*oninput="onCourtFilterChange\(\)"/, 'court search should reset to the first page before rendering');
assert.match(html, /courtPageSize=\d+/, 'court page should keep its own page size state');
assert.match(html, /function setCourtPageSize\(/, 'court page should expose page size switching');
assert.match(html, /function courtDisplayName\(/, 'court page should expose a display-name helper for blank court names');
assert.match(fnBody('courtDisplayName'), /courtStudentNames\(court\)\|\|String\(court\?\.phone\|\|''\)\.trim\(\)\|\|'未命名订场用户'/, 'court blank names should fall back to linked student, phone, then default copy');
assert.match(html, /function courtSortMetric\(/, 'court page should centralize sortable metrics');
assert.match(fnBody('courtSortMetric'), /if\(!raw\|\|raw==='-'\|\|raw==='—'\)return \{empty:true,value:0\};/, 'court date sorting should treat dash placeholders as empty values');
assert.match(fnBody('renderCourts'), /const sortedList=\[\.\.\.list\];/, 'court page should sort the full filtered list before paging');
assert.match(fnBody('renderCourts'), /else\{[\s\S]*updatedAt\|\|b\.createdAt[\s\S]*updatedAt\|\|a\.createdAt/, 'court rows should use a deterministic default sort when no explicit sort is selected');
assert.match(html, /function handleCourtMoreAction\(/, 'court page should expose more action handler');
assert.match(html, /id="courtBatchToolbar"[^>]*style="display:none"/, 'court batch toolbar should stay hidden before entering batch mode');
assert.match(html, /function setCourtBatchMode\(/, 'court page should expose explicit batch mode toggling');
assert.match(html, /function updateCourtBatchButton\([\s\S]*toolbar\.style\.display=courtBatchMode\?'flex':'none'/, 'court batch toolbar should only show in batch mode');
assert.match(html, /function updateCourtBatchButton\([\s\S]*btn\.style\.display=courtBatchMode\?'inline-flex':'none'/, 'court batch delete button should follow batch mode visibility');
assert.match(html, /function renderCourtEmptyText\(/, 'court page should centralize empty dash rendering');
assert.match(html, /return raw&&raw!=='—'\?raw:'-';/, 'court list empty cells should convert long dashes to short dashes');
assert.match(html, /renderCourtDropdownHtml\('nrPayMethod'[\s\S]*'储值扣款',true,'onCourtFinanceSceneChange'\)/, 'court booking payment should default to stored-value deduction');
assert.doesNotMatch(fnBody('saveCourt'), /confirm\(/, 'court save should not use browser confirm');
assert.doesNotMatch(fnBody('saveCourtFinanceRecord'), /confirm\(/, 'court finance save should not use browser confirm');
assert.doesNotMatch(fnBody('renderCourts'), /低余额/, 'court stats should not show low balance text');
assert.match(html, /function courtMembershipTierLabel\(/, 'court membership display should use membership tier label');
assert.match(html, /function courtMembershipTierTagClass\(/, 'court member tier should use tier-specific tag colors');
assert.match(fnBody('renderCourts'), /m\.tierLabel&&m\.tierLabel!=='-'\?`<span class="tms-tag \$\{memberTagClass\}">/, 'current membership should render empty state without a tag');
assert.doesNotMatch(fnBody('renderCourts'), /const memberTagClass=m\.accountType==='会员'\?'tms-tag-green':'';/, 'current membership tag color should not reuse account type tag color');
assert.match(fnBody('renderAll'), /renderPageData\(currentPage\)/, 'initial load should render only the current page instead of every module');
assert.match(html, /function renderCourtFinanceFields\(/, 'court finance modal should render fields by selected scene');
assert.match(html, /function onCourtFinanceSceneChange\(/, 'court finance modal should update visible fields when scene changes');
assert.match(html, /data-finance-field="booking"/, 'court booking-only fields should be scoped');
assert.match(html, /data-finance-field="course"/, 'court course-only fields should be scoped');
assert.match(html, /内部占用/, 'court finance modal should support internal occupancy records');
assert.match(html, /领导打球[\s\S]*活动[\s\S]*测试教学[\s\S]*其他/, 'internal occupancy should provide reason options');
assert.match(html, /data-finance-field="internal"/, 'court finance modal should scope internal-only fields');
assert.match(fnBody('renderCourtFinanceFields'), /const isInternal=type==='消费'&&category==='内部占用';/, 'court finance field visibility should recognize internal occupancy');
assert.match(fnBody('courtFinanceLocal'), /const isInternal=String\(h\.category\|\|''\)\.includes\('内部占用'\);/, 'court finance summary should detect internal occupancy rows');
assert.match(fnBody('courtFinanceLocal'), /else if\(h\.type==='消费'\)\{if\(isInternal\)return;/, 'internal occupancy should not count as direct income or spending totals');
assert.match(fnBody('courtFinanceLocal'), /const hist=currentHistory\.length\?currentHistory:courtBaseHistoryForSave\(c\);/, 'court finance summary should reuse legacy opening history when old records have no explicit history');
assert.match(fnBody('courtFinanceConfirmText'), /内部占用/, 'court finance confirm copy should explain internal occupancy');
assert.match(html, /function courtFinanceRevenueSummaryLocal\(/, 'court page should expose local booking income confirmation summary');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /confirmedRevenue=t\.storedValueBooking\+t\.onsiteBooking/, 'court finance summary should separate confirmed booking revenue');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /pendingRevenue=t\.proxyBooking/, 'court finance summary should separate proxy booking as pending revenue');
assert.match(fnBody('courtFinanceRevenueSummaryLocal'), /matchBooking/, 'court finance summary should expose match booking revenue');
assert.match(fnBody('openCourtFinanceModal'), /确认订场收入[\s\S]*本次实收\/现金流入[\s\S]*待确认\/代用户订场[\s\S]*内部占用次数/, 'court finance modal should show booking income confirmation buckets');
assert.match(fnBody('runBatchDeleteCourts'), /隐藏/, 'batch delete result should explain hidden archived courts');
assert.match(fnBody('renderCourts'), /class="tms-court-row-main"[\s\S]*class="tms-checkbox court-row-cb"/, 'court name cell should separate checkbox and name for easier text selection');
assert.match(fnBody('renderCourts'), /\$\{esc\(courtDisplayName\(u\)\)\}/, 'court rows should render the display-name helper instead of raw names');
assert.doesNotMatch(fnBody('renderCourts'), /<label class="tms-checkbox-wrap"[\s\S]*\$\{esc\(u\.name\)\}/, 'court name text should no longer be wrapped by a clickable label');
assert.match(html, /function openCourtFinanceModal[\s\S]*renderCourtDropdownHtml\('nrStudentId','关联学员'/, 'court finance modal should use a shorter linked-student label');
assert.match(html, /function openCourtFinanceModal[\s\S]*renderCourtDropdownHtml\('nrCompanionCoach','陪打教练'/, 'court finance modal should allow selecting a companion coach for bookings');
assert.match(html, /function saveCourtFinanceRecord[\s\S]*scheduleSource:'订场陪打'/, 'court booking with companion coach should generate a linked coach schedule source');
assert.match(html, /function saveCourtFinanceRecord[\s\S]*courseType:'陪打'/, 'companion coach booking should create a companion schedule type');
assert.match(fnBody('openCourtModal'), /openCourtMergeModal\('/, 'court edit modal should expose a merge entry for existing users');
assert.match(html, /function openCourtMergeModal\(/, 'court page should expose a manual merge modal');
assert.match(html, /function renderCourtMergeTargetOptions\(/, 'court page should expose merge target filtering by search');
assert.match(html, /id="mergeCourtSearch"[^>]*placeholder="搜索姓名"[^>]*oninput="renderCourtMergeTargetOptions\(\)"/, 'merge modal should support searching target users by name');
assert.match(html, /function mergeCourtUsers\(/, 'court page should expose a merge submit handler');

console.log('court page view tests passed');
