const assert = require('assert');
const { appSource: html } = require('./helpers/read-index-bundle');

function fnBody(name){
  const start = html.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(html, /<div class="sb-sec">用户中心<\/div>/, 'sidebar should keep the user-center group');
assert.match(html, /<div class="sb-sec">教学中心<\/div>/, 'sidebar should keep the teaching-center group');
assert.match(html, /<div class="sb-sec">场地运营<\/div>/, 'sidebar should keep the venue-ops group');
assert.match(html, /<div class="sb-sec">资源管理<\/div>/, 'sidebar should keep the resource-management group');

assert.match(html, /goPage\('classes',this\)[\s\S]*?班次管理/, 'sidebar should still keep classes page for historical compatibility');
assert.match(html, /goPage\('products',this\)[\s\S]*?课程产品/, 'sidebar should still keep products page for historical compatibility');
assert.match(html, /style="display:none" onclick="goPage\('classes',this\)"/, 'classes page entry should stay hidden from the active admin nav');
assert.match(html, /style="display:none" onclick="goPage\('products',this\)"/, 'products page entry should stay hidden from the active admin nav');
assert.match(html, /goPage\('packages',this\)[\s\S]*?售卖课包/, 'sidebar should add packages page');
assert.match(html, /goPage\('purchases',this\)[\s\S]*?购买记录/, 'sidebar should add purchases page');
assert.match(html, /goPage\('admin-users',this\)[\s\S]*?账号管理/, 'sidebar should add account management page');
assert.match(html, /goPage\('courts',this\)[\s\S]*?订场用户/, 'sidebar should keep court users in the user-center area');
assert.match(html, /goPage\('memberships',this\)[\s\S]*?会员管理/, 'sidebar should keep memberships in the user-center area');
assert.doesNotMatch(html, /goPage\('entitlements',this\)[\s\S]*?权益账户/, 'sidebar should hide the old entitlement page entry');
assert.match(html, /现行业务主链路是 packages -> purchases -> entitlements -> schedule。/, 'bundle should document the active phase-2 delivery chain');
assert.match(html, /products \/ classes \/ plans 仅保留历史兼容，不应再作为新增功能默认依赖。/, 'bundle should mark old course pages as historical compatibility only');
assert.match(html, /历史兼容模块：课程产品不再作为新增教学售卖功能默认入口。/, 'products page should be treated as a historical shell instead of an active sales entry');
assert.match(html, /历史兼容模块：班次管理暂不作为新增教学售卖链路依赖。/, 'classes page should be treated as a historical shell instead of an active operations entry');
assert.doesNotMatch(html, /goPage\('plans',this\)/, 'sidebar should no longer expose the retired plans page entry');
assert.doesNotMatch(html, /id="page-plans"/, 'html should no longer keep the retired plans page shell');

assert.match(html, /id="page-packages"/, 'should have packages page section');
assert.match(html, /id="page-purchases"/, 'should have purchases page section');
assert.match(html, /course-showcase/, 'course product page should use the new showcase container');
assert.match(html, /course-package-showcase/, 'package page should use the new showcase container');
assert.match(html, /product-card-shell/, 'product page should render the gemini-style product cards');
assert.match(html, /package-card-shell/, 'package page should render the gemini-style package cards');
assert.match(html, /归属教练[\s\S]*购买时选择[\s\S]*可上课教练/, 'package card should distinguish sale owner coach from teachable coaches');
assert.match(html, /主归属教练[\s\S]*可上课教练/, 'purchase records should expose owner coach and teachable coaches');
assert.match(html, /系统价格[\s\S]*实收金额[\s\S]*改价原因/, 'purchase modal should expose system price, actual paid amount and override reason');
assert.doesNotMatch(html, /tms-pill-tabs/, 'sidebar navigation should replace the demo top tabs');
assert.doesNotMatch(html, /const t=\{students:[\s\S]*?\n\s*const t=\{students:/, 'page title map should not be declared twice after merge');
assert.match(html, /workbench:'工作台'/, 'page title map should include coach workbench');
assert.match(html, /归属教练不在这里维护，实际售卖时按购买记录选择/, 'package modal should explain owner coach is selected at purchase time');
assert.match(html, /function productHasReferences/, 'product modal should know whether product is referenced');
assert.match(html, /function packageHasPurchases/, 'package modal should know whether package is sold');
assert.doesNotMatch(fnBody('saveProduct'), /plans\.forEach\(/, 'product save should no longer rewrite retired plans cache');
assert.doesNotMatch(fnBody('renderProducts'), /confirmDel\('\\$\{p\.id\}'/, 'products page should no longer expose delete entry from the historical shell');
assert.match(fnBody('openProductModal'), /历史兼容资料查看/, 'product modal should explicitly present the page as read-only historical data');
assert.doesNotMatch(fnBody('openProductModal'), /productSaveBtn|onclick="saveProduct\(\)"|btn-danger/, 'product modal should no longer expose save or delete actions');
assert.doesNotMatch(fnBody('saveProduct'), /apiCall\('PUT','\/products\/|apiCall\('POST','\/products'|products\.unshift\(|classes\.forEach\(/, 'historical products save handler should no longer perform write actions');
assert.doesNotMatch(html, /历史课程产品已更新 ✓|历史课程产品已保存 ✓/, 'products historical shell should no longer show write-success toasts');
assert.doesNotMatch(fnBody('renderClasses'), /openClassModal\('\$\{c\.id\}'\)|confirmDel\('\$\{c\.id\}'/, 'classes page list should no longer expose edit or delete entries from the historical shell');
assert.doesNotMatch(fnBody('openClassDetail'), /openClassModal\('\$\{c\.id\}'\)|历史校对/, 'class detail should no longer link to historical edit flow');
assert.match(fnBody('openClassModal'), /历史兼容资料查看/, 'class modal should explicitly present the page as read-only historical data');
assert.doesNotMatch(fnBody('openClassModal'), /classSaveBtn|onclick="saveClass\(\)"|补录历史班次|保存后生成编号|选择学员（多选）/, 'class modal should no longer expose create or save behavior');
assert.doesNotMatch(fnBody('saveClass'), /apiCall\('PUT','\/classes\/|apiCall\('POST','\/classes'|classes\.unshift\(|classes\[i\]=saved/, 'historical class save handler should no longer perform write actions');
assert.doesNotMatch(html, /历史班次已更新 ✓|历史班次已保存 ✓/, 'classes historical shell should no longer show write-success toasts');
assert.match(html, /核心字段已锁定/, 'locked core fields should show operator-facing hint');
assert.match(html, /function openPurchaseDetailModal/, 'purchase page should have detail modal');
assert.match(html, /function openPurchaseEditModal/, 'purchase page should have edit modal');
assert.match(html, /function savePurchaseEdit/, 'purchase page should save purchase edits');
assert.match(html, /function openPurchaseModal/, 'purchase page should provide the unified purchase modal');
assert.match(html, /function openPurchaseModal[\s\S]*renderCourtDropdownHtml\('pur_studentId','选择学员'/, 'purchase modal should pick the student in the same step');
assert.match(html, /function openPurchaseModal[\s\S]*支付方式[\s\S]*margin-bottom:0[\s\S]*可上课教练/, 'purchase modal should put pay method and allowed coach fields on separate rows to avoid layout overlap');
assert.match(html, /＋ 课包购买/, 'purchase page should expose a direct package purchase entry button');
assert.match(html, /<th style="width:100px;padding-left:20px">购买日期<\/th><th style="width:120px">学员\/支付<\/th><th style="width:170px">课包\/课程<\/th><th style="width:90px">实收<\/th><th style="width:95px">余额<\/th><th style="width:135px">有效期<\/th><th style="width:80px">状态<\/th><th style="width:95px">归属教练<\/th>/, 'purchase table should split validity and status into compact purchase, balance and owner coach columns');
assert.doesNotMatch(html, /先选择学员[\s\S]*下一步/, 'purchase modal should not require a separate first-step student gate');
assert.match(html, /购买时规则快照/, 'purchase detail should show package snapshot');
assert.match(html, /系统价格[\s\S]*成交金额[\s\S]*改价原因/, 'purchase detail should show price snapshot fields');
assert.match(html, /支付日期[\s\S]*系统录入时间/, 'purchase detail should show business date and system recorded time');
assert.match(html, /function openPurchaseVoidModal/, 'purchase page should use dedicated void modal');
assert.match(html, /function voidPurchase/, 'purchase page should send void reason');
assert.match(html, /作废原因/, 'void modal should require reason');
assert.match(html, /function resolveUniqueStudentIdByText/, 'purchase import should resolve students uniquely');
assert.match(html, /function resolveUniquePackageIdByText/, 'purchase import should resolve packages uniquely');
assert.match(html, /匹配到多个/, 'purchase import should warn duplicate matches');
assert.match(html, /固定使用结束日优先/, 'package modal should explain usage end date priority');
assert.match(html, /真正消课的是课包余额/, 'purchase page should explain package balance purpose');
assert.match(html, /私教课/, 'course pages should expose 私教课 as a fixed type');
assert.match(html, /体验课/, 'course pages should expose 体验课 as a fixed type');
assert.match(html, /训练营/, 'course pages should expose 训练营 as a fixed type');
assert.match(html, /大师课/, 'course pages should expose 大师课 as a fixed type');
assert.doesNotMatch(html, /课程性质/, 'course pages should not mention the removed 课程性质 field');
assert.doesNotMatch(html, /正式课/, 'course pages should not keep the old 正式课 wording');

console.log('course management nav tests passed');
