const assert = require('assert');
const { appSource: source } = require('./helpers/read-index-bundle');

assert.match(source,/goPage\('finance',this\)[\s\S]*?财务中心/,'sidebar should expose finance center page');
assert.match(source,/id="page-finance"/,'finance center page should exist');
assert.match(source,/总账[\s\S]*收入流水[\s\S]*已入账流水[\s\S]*教练结算/,'finance center tabs should follow the simplified order');
assert.match(source,/id="financeTabLedger"/,'finance center should expose ledger tab');
assert.match(source,/id="financeTabRevenue"/,'finance center should expose revenue tab');
assert.match(source,/id="financeTabRecognized"/,'finance center should expose recognized tab');
assert.match(source,/id="financeTabSettlement"/,'finance center should expose settlement tab');
assert.match(source,/id="financeLedgerPanel"/,'finance center should render ledger panel');
assert.match(source,/id="financeRevenuePanel"/,'finance center should render revenue panel');
assert.match(source,/id="financeRecognizedPanel"/,'finance center should render recognized panel');
assert.match(source,/id="financeSettlementPanel"/,'finance center should render settlement panel');
assert.match(source,/function setFinancePanel\(/,'finance center should expose tab switch logic');
assert.match(source,/let coachOpsMode='day',coachOpsPanel='schedule',coachOpsPickerMonth=null,financePanel='ledger'/,'finance center should default to ledger tab');
assert.match(source,/function renderFinanceCenter\(/,'finance center should expose page render logic');
assert.match(source,/function renderFinanceOverview\(/,'finance center should render summary stats inside ledger tab');
assert.match(source,/function renderFinanceLedger\(/,'finance center should render ledger table');
assert.match(source,/function renderFinanceRevenueReport\(/,'finance center should render revenue detail table');
assert.match(source,/function renderFinanceConsumeReport\(/,'finance center should render consume detail table');
assert.match(source,/function renderFinanceSettlementSummary\(/,'finance center should render settlement summary');
assert.match(source,/id="financeLedgerBusinessTypeFilterHost"/,'ledger should expose business type filter host');
assert.match(source,/id="financeLedgerActionFilterHost"/,'ledger should expose action filter host');
assert.match(source,/id="financeLedgerPayMethodFilterHost"/,'ledger should expose pay method filter host');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerBusinessTypeFilter'/,'ledger business type filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerActionFilter'/,'ledger action filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeLedgerPayMethodFilter'/,'ledger pay method filter should reuse shared dropdown style');
assert.match(source,/id="financeRevenueTypeFilterHost"/,'revenue table should expose income type filter host');
assert.match(source,/id="financeRevenuePayMethodFilterHost"/,'revenue table should expose pay method filter host');
assert.match(source,/renderCourtDropdownHtml\('financeRevenueTypeFilter'/,'revenue type filter should reuse shared dropdown style');
assert.match(source,/renderCourtDropdownHtml\('financeRevenuePayMethodFilter'/,'revenue pay method filter should reuse shared dropdown style');
assert.match(source,/日期[\s\S]*星期[\s\S]*时间段[\s\S]*客户[\s\S]*收入类型[\s\S]*支付方式[\s\S]*应收[\s\S]*实收[\s\S]*差价[\s\S]*差价说明[\s\S]*收款人[\s\S]*备注[\s\S]*校区[\s\S]*状态[\s\S]*关联单据[\s\S]*financeRevenueTbody/,'revenue table should follow the manual sheet column order');
assert.match(source,/确认日期[\s\S]*客户[\s\S]*确认类型[\s\S]*来源项目[\s\S]*扣减标的[\s\S]*确认收入[\s\S]*校区[\s\S]*状态[\s\S]*关联单据[\s\S]*financeConsumeTbody/,'consume table should explain where recognized revenue comes from');
assert.match(source,/业务日期[\s\S]*客户[\s\S]*校区[\s\S]*业务类型[\s\S]*动作[\s\S]*实收[\s\S]*已入账[\s\S]*未入账[\s\S]*支付方式[\s\S]*来源单据[\s\S]*备注[\s\S]*financeLedgerTbody/,'ledger table should use plain-language columns');
assert.match(source,/courtDateButtonHtml\(id,value,label,handler\)/,'finance date controls should refresh reports after selecting a date');
assert.match(source,/renderFinanceLedgerReport\(\)">查询|renderFinanceLedger\(\)">查询/,'ledger date filters should have an explicit query button');
assert.match(source,/renderFinanceRevenueReport\(\)">查询/,'revenue date filters should have an explicit query button');
assert.match(source,/renderFinanceConsumeReport\(\)">查询/,'consume date filters should have an explicit query button');
assert.doesNotMatch(source,/未入账明细/,'ledger should no longer show a second prepaid detail table');
assert.match(source,/总收入（实收）[\s\S]*总已入账[\s\S]*总未入账/,'ledger summary should use plain-language owner terms');
assert.doesNotMatch(source,/总流水笔数/,'ledger summary should not keep total flow count card');
assert.match(source,/课包收入 \/ 已入账[\s\S]*会员储值收入 \/ 已消耗[\s\S]*订场收入 \/ 已入账/,'ledger summary should keep six owner-facing cards without duplicate member booking stats');
assert.doesNotMatch(source,/会员订场已入账/,'ledger summary should not repeat stored value consumption as a separate member booking card');
assert.match(source,/id="financeLedgerPagerInfo"/,'ledger should expose pager info');
assert.match(source,/id="financeLedgerPageSize"/,'ledger should expose page size selector');
assert.match(source,/id="financeLedgerPagerBtns"/,'ledger should expose pager buttons');
assert.match(source,/function setFinanceLedgerPageSize\(/,'ledger should support switching page size');
assert.match(source,/function setFinanceLedgerPage\(/,'ledger should support switching pages');
assert.match(source,/20条\/页[\s\S]*50条\/页[\s\S]*100条\/页/,'ledger page size selector should offer 20, 50, and 100 rows per page');
assert.match(source,/查看迟到月结/,'finance center should expose late settlement entry');

console.log('finance page view tests passed');
