const assert = require('assert');
const fs = require('fs');
const path = require('path');

const apiSource = fs.readFileSync(path.join(__dirname, '../api/index.js'), 'utf8');
const routeSource = fs.readFileSync(path.join(__dirname, '../api/teaching/route-handlers.js'), 'utf8');
const courtsMembershipSource = fs.readFileSync(path.join(__dirname, '../api/courts-membership/route-handlers.js'), 'utf8');
const membershipWriteSource = fs.readFileSync(path.join(__dirname, '../api/membership/write-handlers.js'), 'utf8');
const pageDataSource = fs.readFileSync(path.join(__dirname, '../api/page-data/aggregate-handlers.js'), 'utf8');
const financeReadModelSource = fs.readFileSync(path.join(__dirname, '../api/page-data/finance-read-model.js'), 'utf8');
const authAdminSource = fs.readFileSync(path.join(__dirname, '../api/auth-admin/route-handlers.js'), 'utf8');
const initRuntimeSource = fs.readFileSync(path.join(__dirname, '../api/bootstrap/init-runtime.js'), 'utf8');
const matchSource = fs.readFileSync(path.join(__dirname, '../api/matches/index.js'), 'utf8');
function sectionBetween(source,startMarker,endMarker){
  const start=source.indexOf(startMarker);
  const end=source.indexOf(endMarker,start);
  assert.ok(start>=0&&end>start, `missing source section: ${startMarker}`);
  return source.slice(start,end);
}
const studentReferenceSection=sectionBetween(apiSource,'async function loadStudentReferenceData(){','async function applyStudentIdentityUpdate');

assert.match(apiSource, /const HOT_SCAN_TABLES=new Map\(/, 'api should declare hot table cache config');
assert.match(apiSource, /const HOT_GET_TABLES=new Map\(/, 'api should declare hot row cache config');
assert.match(apiSource, /const HOT_CACHE_TTL_MS=\d+\s*\*\s*60\s*\*\s*1000;/, 'api should centralize hot cache ttl so global tuning does not require editing every table entry');
assert.match(apiSource, /function getCachedScan\(t\)/, 'api should expose a cached scan helper');
assert.match(apiSource, /function getCachedRow\(t,id\)/, 'api should expose a cached row helper');
assert.match(apiSource, /function invalidateHotScanCache\(t\)/, 'api should expose cache invalidation');
assert.match(apiSource, /function invalidateHotGetCache\(t,id\)/, 'api should expose row cache invalidation');
assert.match(apiSource, /if\(HOT_SCAN_TABLES\.has\(t\)\)invalidateHotScanCache\(t\);/, 'writes should invalidate hot table cache');
assert.match(apiSource, /if\(HOT_GET_TABLES\.has\(t\)\)invalidateHotGetCache\(t,id\);/, 'writes should invalidate hot row cache');
assert.match(routeSource, /if\(path==='\/students'\)\{[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)\{[\s\S]*const rows=await getCachedScan\(tables\.students\);/, 'students list should use cached scan');
assert.match(routeSource, /if\(user\.role==='admin'\)return sendJson\(res,rows\);[\s\S]*filterLoadAllForUser\(\{students:rows,schedule,classes,coaches\},user,coachRefs\)\.students/, 'coach students list should filter cached scan results');
assert.match(courtsMembershipSource, /if\(path==='\/courts'\)\{[\s\S]*if\(method==='GET'\)return \{body:await getCachedScan\(tables\.courts\)\};/, 'courts list should use cached scan');
assert.match(routeSource, /if\(path==='\/schedule'\)\{[\s\S]*if\(method==='GET'\)\{[\s\S]*const rows=await getCachedScan\(tables\.schedule\);/, 'schedule list should use cached scan');
assert.match(routeSource, /if\(path==='\/classes'\)\{[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)\{[\s\S]*const rows=await getCachedScan\(tables\.classes\);/, 'classes list should use cached scan');
assert.match(routeSource, /if\(path==='\/coaches'\)\{[\s\S]*if\(user\.role!=='admin'\)return sendJson\(res,\{error:'无权限'\},403\);[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)return sendJson\(res,await getCachedScan\(tables\.coaches\)\);/, 'coaches list should use cached scan');
assert.match(apiSource, /async function listCampusesWithDefaults\(\)\{[\s\S]*const rows=await getCachedScan\(T_CAMPUSES\)\.catch\(\(\)=>\[\]\);[\s\S]*return rows\.length\?rows:DEFAULT_CAMPUSES;/, 'campuses should read through cached scan with default fallback');
assert.match(apiSource, /if\(path==='\/campuses'\)\{await init\(\);if\(method==='GET'\)return sendJson\(res,await listCampusesWithDefaults\(\)\);/, 'campuses list should use cached scan via the default-aware helper');
assert.doesNotMatch(apiSource, /\[T_PLANS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'plans should be removed from hot scan tables');
assert.match(apiSource, /\[T_ENTITLEMENTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'entitlements should be configured as a hot scan table');
assert.match(apiSource, /\[T_PRODUCTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'products should be configured as a hot scan table');
assert.match(apiSource, /\[T_PACKAGES,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'packages should be configured as a hot scan table');
assert.match(apiSource, /\[T_PURCHASES,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'purchases should be configured as a hot scan table');
assert.match(apiSource, /\[T_MEMBERSHIP_ACCOUNTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership accounts should be configured as a hot scan table');
assert.match(apiSource, /\[T_MEMBERSHIP_ORDERS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership orders should be configured as a hot scan table');
assert.match(apiSource, /\[T_MEMBERSHIP_BENEFIT_LEDGER,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership benefit ledger should be configured as a hot scan table');
assert.match(apiSource, /\[T_ENTITLEMENT_LEDGER,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'entitlement ledger should be configured as a hot scan table');
assert.match(apiSource, /\[T_CLASSES,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'classes should be configured as a hot row cache');
assert.match(apiSource, /\[T_ENTITLEMENTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'entitlements should be configured as a hot row cache');
assert.match(apiSource, /\[T_COURTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'court detail should be configured as a hot row cache');
assert.match(apiSource, /\[T_MEMBERSHIP_PLANS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership plan detail should be configured as a hot row cache');
assert.match(apiSource, /\[T_MEMBERSHIP_ACCOUNTS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership account detail should be configured as a hot row cache');
assert.match(apiSource, /\[T_MEMBERSHIP_ORDERS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'membership order detail should be configured as a hot row cache');
assert.match(apiSource, /\[T_PRICE_PLANS,\{ttlMs:HOT_CACHE_TTL_MS\}\]/, 'price plan detail should be configured as a hot row cache');
assert.match(apiSource, /async function applyLessonDelta\(classId,delta,studentIds=\[\]\)\{[\s\S]*const cls=await getCachedRow\(T_CLASSES,classId\);/, 'lesson delta should reuse cached class row');
assert.doesNotMatch(apiSource, /scan plans for lesson delta|getCachedScan\(T_PLANS\)[\s\S]*usedLessons:nextPlanUsed|put\(T_PLANS,/, 'lesson delta should stop maintaining retired plans rows');
assert.match(apiSource, /async function assertScheduleEntitlementCapacity\(nextRec,oldRec\)\{[\s\S]*const ent=await getCachedRow\(T_ENTITLEMENTS,nextDelta\.entitlementId\);/, 'schedule entitlement capacity should reuse cached entitlement row');
assert.match(apiSource, /async function applyEntitlementDelta\(entitlementId,scheduleId,delta,action,reason,user\)\{[\s\S]*const ent=await getCachedRow\(T_ENTITLEMENTS,entitlementId\);/, 'schedule entitlement writes should reuse cached entitlement row');
assert.match(routeSource, /if\(path==='\/entitlements'\)\{[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)\{[\s\S]*const rows=await getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\);/, 'entitlement list should use cached scan');
assert.match(routeSource, /if\(path==='\/entitlements\/recommend'&&method==='POST'\)\{[\s\S]*await init\(\);[\s\S]*getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\)/, 'entitlement recommend should use cached scan');
assert.match(routeSource, /if\(method==='GET'\)return sendJson\(res,await getCachedRow\(tables\.entitlements,id\)\);/, 'entitlement detail should use cached row');
assert.match(apiSource, /async function validateScheduleSave\(nextRec,oldRec\)\{[\s\S]*timed\('scan schedule for conflict check',\(\)=>getCachedScan\(T_SCHEDULE\)\)[\s\S]*timed\('scan courts for schedule conflict check',\(\)=>getCachedScan\(T_COURTS\)\.catch\(\(\)=>\[\]\)\)/, 'schedule save validation should reuse cached schedule and court scans');
assert.doesNotMatch(apiSource, /async function syncClassPlans\(classId,cls\)\{/, 'class plan sync should be removed');
assert.doesNotMatch(apiSource, /buildCoachRenameUpdates\([\s\S]*plans:\(data\.plans\|\|\[\]\)/, 'coach rename should stop maintaining retired plans rows');
assert.doesNotMatch(apiSource, /loadCoachReferenceData\(\)[\s\S]*scan plans for coach references/, 'coach reference loading should stop scanning retired plans rows');
assert.doesNotMatch(apiSource, /buildStudentIdentityUpdates\([\s\S]*plans:\(data\.plans\|\|\[\]\)/, 'student rename should stop maintaining retired plans rows');
assert.match(apiSource, /async function loadStudentReferenceData\(\)\{[\s\S]*getCachedScan\(T_SCHEDULE\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(T_ENTITLEMENTS\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(T_COURTS\)\.catch\(\(\)=>\[\]\)/, 'student identity update should reuse cached scans for active linked tables');
assert.doesNotMatch(studentReferenceSection, /getCachedScan\(T_PLANS\)/, 'student reference loading should stop scanning retired plans rows');
assert.doesNotMatch(apiSource, /buildProductRenameDisplayUpdates\([\s\S]*const plans=\(data\.plans\|\|\[\]\)/, 'product rename should stop preparing retired plans rows');
assert.match(routeSource, /const \[entitlementRows,coachRows,userRows\]=await Promise\.all\(\[[\s\S]*getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\)/, 'schedule create should reuse cached entitlement scan');
assert.match(routeSource, /const entitlementDeltas=resolveScheduleEntitlementDeltas\(\{\.\.\.r,coachRefs\},entitlementRows\);/, 'schedule create should reuse cached entitlement scan');
assert.match(routeSource, /const \[entitlementRows,coachRows,userRows\]=await Promise\.all\(\[[\s\S]*getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\)/, 'schedule edit should reuse cached entitlement scan');
assert.match(routeSource, /assertCanEditClassWithSchedules\(old,r,await getCachedScan\(tables\.schedule\)\);/, 'class edit should reuse cached schedule scan');
assert.doesNotMatch(routeSource, /assertCanDeleteClass\(id,await getCachedScan\(tables\.schedule\)\);[\s\S]*getCachedScan\(tables\.plans\)/, 'class delete should stop scanning retired plans rows');
assert.match(apiSource, /async function prewarmHotScanCache\(\)/, 'api should expose a hot table prewarm');
assert.match(initRuntimeSource, /prewarmHotScanCache\(\)\.catch\(\(err\) => logger\.error\('\[api-timing\] prewarm hot tables failed', err\)\);/, 'init should trigger hot table prewarm');
assert.match(matchSource, /const storedAuthUser=await getCachedRow\(T_USERS,user\.id\)\.catch\(\(\)=>null\);/, 'authenticated requests should reuse cached user row lookup');
assert.match(authAdminSource, /async function loadLoginAccount\(username\)\{[\s\S]*withDeadline\(getCachedRow\(tables\.users,username\),loginRowTimeoutMs,[\s\S]*getCachedScan\(tables\.users\)\.catch\(\(err\)=>\{[\s\S]*if\(account\?\.__loginTimeout\)return \{status:503,body:\{error:LOGIN_STORAGE_TIMEOUT_ERROR\}\};/, 'login should fallback from ft_users row timeout to cached user scan and surface 503 when both lookups time out');
assert.match(routeSource, /if\(path==='\/products'\)\{[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)return sendJson\(res,await getCachedScan\(tables\.products\)\.catch\(\(\)=>\[\]\)\);/, 'products list should use cached scan');
assert.match(routeSource, /if\(path==='\/packages'\)\{[\s\S]*if\(user\.role!=='admin'\)return sendJson\(res,\{error:'无权限'\},403\);[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)return sendJson\(res,await getCachedScan\(tables\.packages\)\.catch\(\(\)=>\[\]\)\);/, 'packages list should use cached scan');
assert.match(routeSource, /if\(path==='\/purchases'\)\{[\s\S]*if\(user\.role!=='admin'\)return sendJson\(res,\{error:'无权限'\},403\);[\s\S]*await init\(\);[\s\S]*if\(method==='GET'\)return sendJson\(res,await getCachedScan\(tables\.purchases\)\.catch\(\(\)=>\[\]\)\);/, 'purchases list should use cached scan');
assert.match(courtsMembershipSource, /if\(path==='\/membership-accounts'\)\{[\s\S]*if\(method==='GET'\)\{[\s\S]*const rows=await getCachedScan\(tables\.membershipAccounts\)\.catch\(\(\)=>\[\]\);/, 'membership accounts list should use cached scan');
assert.match(membershipWriteSource, /if\(path==='\/membership-orders'\)\{[\s\S]*if\(method==='GET'\)return \{body:await getCachedScan\(tables\.membershipOrders\)\.catch\(\(\)=>\[\]\)\};/, 'membership orders list should use cached scan');
assert.match(apiSource, /async function loadCourtDeleteReferenceData\(\)\{[\s\S]*getCachedScan\(T_MEMBERSHIP_ACCOUNTS\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(T_MEMBERSHIP_ORDERS\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(T_MEMBERSHIP_BENEFIT_LEDGER\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(T_MEMBERSHIP_ACCOUNT_EVENTS\)\.catch\(\(\)=>\[\]\)/, 'court delete and merge reference checks should reuse cached membership scans');
assert.match(apiSource, /async function deleteCourtsByIds\(ids,data=\{\}\)\{[\s\S]*const courts=await getCachedScan\(T_COURTS\)\.catch\(\(\)=>\[\]\);/, 'batch court delete should reuse cached court scan');
assert.match(apiSource, /async function runMembershipReconcile\(rows\)\{[\s\S]*await getCachedScan\(T_MEMBERSHIP_ACCOUNTS\)\.catch\(\(\)=>\[\]\)[\s\S]*await getCachedScan\(T_COURTS\)\.catch\(\(\)=>\[\]\)/, 'membership reconcile should reuse cached account and court scans');
assert.match(courtsMembershipSource, /if\(method==='GET'\)return \{body:await getCachedRow\(tables\.membershipPlans,id\)\};/, 'membership plan detail should use cached row');
assert.match(courtsMembershipSource, /const old=await getCachedRow\(tables\.membershipPlans,id\)\.catch\(\(\)=>null\);[\s\S]*const orders=await getCachedScan\(tables\.membershipOrders\)\.catch\(\(\)=>\[\]\);/, 'membership plan edit and delete checks should use cache');
assert.match(courtsMembershipSource, /if\(method==='GET'\)return \{body:await getCachedRow\(tables\.membershipAccounts,id\)\};/, 'membership account detail should use cached row');
assert.match(courtsMembershipSource, /const old=await getCachedRow\(tables\.membershipAccounts,id\)\.catch\(\(\)=>null\);/, 'membership account edit should use cached row');
assert.match(membershipWriteSource, /const \[court,plan,existingAccountFallback\]=await Promise\.all\(\[[\s\S]*getCachedRow\(tables\.courts,body\.courtId\)\.catch\(\(\)=>null\)[\s\S]*getCachedRow\(tables\.membershipPlans,body\.membershipPlanId\)\.catch\(\(\)=>null\)[\s\S]*body\.membershipAccountId\?getCachedRow\(tables\.membershipAccounts,body\.membershipAccountId\)\.catch\(\(\)=>null\):Promise\.resolve\(null\)/, 'membership order create should use cached court plan and account rows');
assert.match(membershipWriteSource, /const existingAccount=existingAccountFallback&&existingAccountFallback\.courtId===court\.id&&existingAccountFallback\.status!=='voided'[\s\S]*:\s*\(await getCachedScan\(tables\.membershipAccounts\)\.catch\(\(\)=>\[\]\)\)\.find/, 'membership order account fallback should reuse cached account scan');
assert.match(membershipWriteSource, /if\(method==='GET'\)return \{body:await getCachedRow\(tables\.membershipOrders,id\)\};/, 'membership order detail should use cached row');
assert.match(membershipWriteSource, /const old=await getCachedRow\(tables\.membershipOrders,id\)\.catch\(\(\)=>null\);/, 'membership order updates should use cached row');
assert.match(membershipWriteSource, /const account=body\.membershipAccountId\?await getCachedRow\(tables\.membershipAccounts,body\.membershipAccountId\)\.catch\(\(\)=>null\):null;/, 'membership benefit ledger manual updates should reuse cached account row');
assert.match(membershipWriteSource, /const \[orders,ledger\]=await Promise\.all\(\[[\s\S]*getCachedScan\(tables\.membershipOrders\)\.catch\(\(\)=>\[\]\),[\s\S]*getCachedScan\(tables\.membershipBenefitLedger\)\.catch\(\(\)=>\[\]\)[\s\S]*\]\);/, 'membership benefit allocation should reuse cached order and ledger scans');
assert.match(membershipWriteSource, /const plans=needsPlanFallback\?await getCachedScan\(tables\.membershipPlans\)\.catch\(\(\)=>\[\]\):\[\];/, 'membership benefit allocation plan fallback should reuse cached plan scan');
assert.match(courtsMembershipSource, /const prev=await getCachedRow\(tables\.courts,id\)\.catch\(\(\)=>null\);[\s\S]*const schedules=prevHistory===nextHistory\?\[\]:await getCachedScan\(tables\.schedule\)\.catch\(\(\)=>\[\]\);/, 'court edit should reuse cached row and schedule scan');
assert.match(courtsMembershipSource, /const court=await getCachedRow\(tables\.courts,id\)\.catch\(\(\)=>null\);/, 'court delete should reuse cached row');
assert.doesNotMatch(apiSource, /if\(path==='\/page-data\/plans'&&method==='GET'\)\{/, 'retired plans page should no longer keep an aggregated endpoint');
assert.match(pageDataSource, /if\(path==='\/page-data\/purchases'\)\{[\s\S]*Promise\.all\(\[[\s\S]*getCachedScan\(tables\.purchases\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.packages\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.students\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\)[\s\S]*\]\)/, 'purchases page aggregate endpoint should reuse cached scans on the server side');
assert.match(pageDataSource, /if\(path==='\/page-data\/finance'\)\{[\s\S]*return \{body:await loadFinancePageData\(\)\};/, 'finance page aggregate endpoint should delegate to the dedicated finance read model');
assert.match(financeReadModelSource, /listCampusesWithDefaults\(\)[\s\S]*getCachedScan\(tables\.students\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.schedule\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.entitlements\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.entitlementLedger\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.coaches\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.products\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.purchases\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.packages\)\.catch\(\(\)=>\[\]\)/, 'finance read model should reuse cached scans on the server side');
assert.match(pageDataSource, /if\(path==='\/page-data\/courts'\)\{[\s\S]*Promise\.all\(\[[\s\S]*listCampusesWithDefaults\(\)[\s\S]*getCachedScan\(tables\.students\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.courts\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipAccounts\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.coaches\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.pricePlans\)\.catch\(\(\)=>\[\]\)[\s\S]*\]\)/, 'courts page aggregate endpoint should reuse cached scans on the server side');
assert.match(pageDataSource, /if\(path==='\/page-data\/memberships'\)\{[\s\S]*Promise\.all\(\[[\s\S]*listCampusesWithDefaults\(\)[\s\S]*getCachedScan\(tables\.students\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.courts\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipAccounts\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipOrders\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipBenefitLedger\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipAccountEvents\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.membershipPlans\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.coaches\)\.catch\(\(\)=>\[\]\)[\s\S]*\]\)/, 'memberships page aggregate endpoint should reuse cached scans on the server side');
assert.match(apiSource, /async function getCachedFeedbacks\(\)\{[\s\S]*getCachedScan\(T_FEEDBACKS\)\.catch\(err=>\{/, 'feedback reads should reuse hot cache with a missing-table fallback');
assert.match(pageDataSource, /if\(path==='\/page-data\/workbench'\)\{[\s\S]*Promise\.all\(\[[\s\S]*listCampusesWithDefaults\(\)[\s\S]*getCachedScan\(tables\.students\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.classes\)\.catch\(\(\)=>\[\]\)[\s\S]*getCachedScan\(tables\.schedule\)\.catch\(\(\)=>\[\]\)[\s\S]*withTimeout\(getCachedFeedbacks\(\),3000,\[\]\)[\s\S]*\]\)/, 'workbench page aggregate endpoint should reuse cached scans and cached feedback fallback on the server side');
assert.match(apiSource, /scan\(T_MEMBERSHIP_BENEFIT_LEDGER\)\.catch\(\(\)=>\[\]\)/, 'membership benefit ledger should keep a safe fallback path');

console.log('hot table cache tests passed');
