const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '../public/index.html'), 'utf8');

assert.match(html, /goPage\('memberships',this\)[\s\S]*?会员管理/, 'sidebar should add membership management entry');
assert.match(html, /id="page-memberships"/, 'should have memberships page section');
assert.match(html, /会员方案[\s\S]*会员购买[\s\S]*会员账户[\s\S]*赠送权益/, 'membership page should include four management views');
assert.match(html, /let membershipTab='accounts';/, 'membership page should default to account overview');

assert.match(html, /let courts=\[\],students=\[\],products=\[\],packages=\[\],purchases=\[\],entitlements=\[\],entitlementLedger=\[\],membershipPlans=\[\],membershipAccounts=\[\],membershipOrders=\[\],membershipBenefitLedger=\[\],membershipAccountEvents=\[\]/, 'frontend state should load membership data separately');
assert.match(html, /membershipPlans=Array\.isArray\(data\?\.membershipPlans\)\?data\.membershipPlans:\[\]/, 'load-all should store membership plans');
assert.match(html, /membershipAccounts=Array\.isArray\(data\?\.membershipAccounts\)\?data\.membershipAccounts:\[\]/, 'load-all should store membership accounts');
assert.match(html, /membershipOrders=Array\.isArray\(data\?\.membershipOrders\)\?data\.membershipOrders:\[\]/, 'load-all should store membership orders');
assert.match(html, /membershipBenefitLedger=Array\.isArray\(data\?\.membershipBenefitLedger\)\?data\.membershipBenefitLedger:\[\]/, 'load-all should store membership benefit ledger');

assert.match(html, /账户类型[\s\S]*当前会员[\s\S]*会员状态[\s\S]*当前折扣[\s\S]*会员到期/, 'courts table should show membership status columns');
assert.match(html, /function courtMembershipSummary/, 'courts page should compute membership summaries');
assert.match(html, /查看账户/, 'courts table should expose dedicated membership account entry');
assert.match(html, /编辑资料/, 'courts table should keep profile editing entry');
assert.match(html, /function openCourtMembershipPanel/, 'membership actions should move into dedicated account panel');
assert.match(html, /function courtMembershipPanelHtml/, 'membership account should render through dedicated panel html');
assert.match(html, /当前状态[\s\S]*权益批次[\s\S]*最近购买记录[\s\S]*操作/, 'membership account panel should keep four sections');
assert.match(html, /会员账户[\s\S]*余额来自 courts\.history，仅展示不可直接修改/, 'membership account panel should explain balance source');
assert.match(html, /消耗权益[\s\S]*补发权益[\s\S]*查看流水/, 'membership account panel should expose structured benefit actions');
assert.match(html, /function courtMembershipBenefitRowsHtml/, 'membership account panel should render benefit rows');
assert.match(html, /function membershipBenefitBatchCardsHtml/, 'membership account panel should render benefit batches by order');
assert.match(html, /购买日期[\s\S]*方案名[\s\S]*批次到期/, 'membership batches should show purchase date, plan and expiry');
assert.match(html, /function membershipActionVisibility/, 'membership account panel should compute action visibility by status');
assert.match(html, /if\(\['voided','cleared'\]\.includes\(account\.status\)\)return \{reopen:true,ledger:true\}/, 'reopen should only be available for voided or cleared accounts');
assert.match(html, /已作废[\s\S]*折扣失效[\s\S]*权益不可再使用/, 'voided account panel should explain disabled discount and benefits');
assert.match(html, /重新开卡[\s\S]*查看流水/, 'voided or cleared accounts should keep reopen and ledger only');
assert.match(html, /function openMembershipBenefitActionModal/, 'benefit actions should use dedicated modal');
assert.match(html, /function membershipBenefitConsumePreview/, 'benefit consume modal should build batch preview');
assert.match(html, /当前总剩余[\s\S]*优先扣减批次/, 'benefit consume modal should explain batch allocation');
assert.match(html, /如果当前批次不足，将继续扣减下一批/, 'benefit consume modal should explain cross-batch deduction');
assert.match(html, /本次补发会记入所选购买批次的权益调整，不会生成新的购买记录/, 'supplement modal should explain existing-batch attribution');
assert.match(html, /function openMembershipBenefitHistoryModal/, 'benefit history should have dedicated modal');
assert.match(html, /查看明细/, 'benefit card should use shorter history label');
assert.match(html, /查看全部权益流水/, 'court detail should provide all-benefit history entry for the current user');
assert.match(html, /function openCourtMembershipLedgerModal/, 'court detail should support all-benefit history modal');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','consume'\)/, 'court detail shortcut actions should not hardcode ballMachine consume');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','supplement'\)/, 'court detail shortcut actions should not hardcode ballMachine supplement');
assert.doesNotMatch(html, /openMembershipBenefitHistoryModal\('\$\{court\.id\}','ballMachine'\)/, 'court detail shortcut actions should not hardcode ballMachine history');

assert.match(html, /function studentMembershipSummaryHtml/, 'student detail should render linked court membership summary');
assert.match(html, /关联订场账户会员摘要/, 'student detail should label linked membership summary');
assert.match(html, /大师公开课[\s\S]*穿线免手工费[\s\S]*发球机免费[\s\S]*国家二级运动员陪打[\s\S]*指定教练陪打/, 'membership plan form should expose structured benefit fields');
assert.match(html, /余额有效期按购买日起算 12 个月/, 'membership purchase flow should surface balance validity rule');
assert.match(html, /若到期时仍有余额，可自动进入延续期，最长至 24 个月/, 'membership purchase flow should surface extended validity rule');
assert.match(html, /低于原合规档位续充时，余额有效期不会重置/, 'membership purchase flow should warn when low-tier renewal does not reset validity');
assert.match(html, /余额来自 courts\.history，仅展示不可直接修改/, 'membership views should explain balance source');
assert.match(html, /每批赠送权益有效期 12 个月/, 'membership purchase flow should surface benefit batch validity rule');
assert.match(html, /function membershipOrderPreview/, 'membership order modal should build preview data');
assert.match(html, /function openMembershipOrderModal\(courtId,mode='renew'\)/, 'membership order modal should support first open renew and reopen modes');
assert.match(html, /本次会发生什么/, 'membership order modal should show change preview first');
assert.match(html, /是否重置有效期[\s\S]*折扣变化[\s\S]*原有权益保留[\s\S]*本次新增权益/, 'membership order preview should explain the main impact clearly');
assert.match(html, /<details[\s\S]*本次额外赠送/, 'one-time adjustments should still exist but be collapsed by default');
assert.match(html, /我了解折扣和有效期变化，确认续充/, 'low-tier renewal should use stronger confirm wording');
assert.match(html, /function membershipOrderDraftFromPlan/, 'membership order modal should derive one-time benefit draft from selected plan');
assert.match(html, /function membershipStepperHtml/, 'membership forms should use stepper helper');
assert.match(html, /function membershipPlanPreviewHtml/, 'membership plan form should render realtime preview');
assert.match(html, /function refreshMembershipPlanPreview/, 'membership plan form should refresh preview on input');
assert.doesNotMatch(html, /id="mp_discount"[^>]*value="1"/, 'membership plan discount should not force default value 1 in html');
assert.doesNotMatch(html, /例如 8 折填 0\.8/, 'membership plan discount should not ask operators to type decimal discount');
assert.match(html, /<select class="fselect" id="mp_discount"/, 'membership plan discount should use option select');
assert.doesNotMatch(html, /id="mp_publicLesson"[^>]*value="0"/, 'membership plan benefit inputs should not force default zero in html');
assert.doesNotMatch(html, /id="mo_publicLesson"[^>]*value="0"/, 'membership order adjustment inputs should not force default zero in html');
assert.match(html, /本次额外赠送/, 'membership order modal should allow one-time benefit adjustments');
assert.match(html, /大师公开课本次调整[\s\S]*穿线免手工费本次调整[\s\S]*发球机免费本次调整[\s\S]*国家二级运动员陪打本次调整[\s\S]*指定教练陪打本次调整/, 'membership order modal should expose one-time benefit adjustment fields');
assert.match(html, /指定教练范围本次调整/, 'membership order modal should expose one-time designated coach override');
assert.match(html, /选择指定教练/, 'membership plan and order forms should use coach-linked designated coach selector');
assert.match(html, /function membershipCoachSelectorHtml/, 'designated coach selection should be rendered by helper');
assert.match(html, /coaches\.map/, 'designated coach selector should be linked to coach records');
assert.match(html, /function membershipOrderBenefitSummaryHtml/, 'membership purchase list should render readable benefit batch summary');
assert.match(html, /额外赠送/, 'membership purchase list should show one-off extra benefit adjustments');
assert.match(html, /购买日期[\s\S]*订场用户[\s\S]*会员方案[\s\S]*充值[\s\S]*赠送金额[\s\S]*折扣[\s\S]*是否重置有效期[\s\S]*当次权益摘要[\s\S]*状态/, 'membership purchase page should be reduced to audit fields');
assert.match(html, /此页面仅用于审计与追溯，不用于日常操作/, 'audit pages should explain read-only positioning');
assert.match(html, /会员数[\s\S]*订购次数[\s\S]*总金额[\s\S]*30天内到期/, 'membership accounts home should show current-phase summary cards');
assert.match(html, /方案配置[\s\S]*购买记录[\s\S]*权益流水/, 'membership accounts home should expose secondary navigation actions');
assert.match(html, /权益有效期固定 12 个月[\s\S]*余额最长按当前系统规则至 24 个月/, 'membership plan form should explain fixed validity rules');
assert.match(html, /可用权益/, 'membership account list should expose benefit summary');
assert.match(html, /查看账户/, 'membership account list should expose account detail entry');
assert.match(html, /function membershipDisplayStatus/, 'frontend should compute display status labels');
assert.match(html, /function membershipValidityHint/, 'frontend should compute validity hint text');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*开通会员/, 'court edit modal should not include membership open action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*续充会员/, 'court edit modal should not include membership renew action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*消耗 1 次/, 'court edit modal should not include benefit consume action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*补发/, 'court edit modal should not include benefit supplement action');
assert.match(html, /function normalizeCurrentPageForRole/, 'frontend should normalize landing page by role before rendering');
assert.match(html, /function renderRoleShell/, 'frontend should centralize role shell rendering');
assert.match(html, /applyLoadedData[\s\S]*normalizeCurrentPageForRole\(\);[\s\S]*renderRoleShell\(\);/, 'load-all should re-sync shell after user role changes');
assert.match(html, /function clearLoadedData/, 'frontend should clear stale data when login\/load-all fails');
assert.match(html, /let lastDataSyncAt=0,isSyncingAll=false,dataRequestVersion=0;/, 'frontend should track request version to ignore stale load-all responses');
assert.match(html, /const requestVersion=\+\+dataRequestVersion;[\s\S]*if\(requestVersion!==dataRequestVersion\)return;/, 'load-all and background sync should ignore stale responses from older sessions');
assert.match(html, /clearLoadedData\(\);[\s\S]*buildCampusTabs\(\);[\s\S]*renderAll\(\);[\s\S]*toast\('加载失败：'/, 'load-all failure should clear stale data and stale campus tabs before showing error');
assert.match(html, /if\(!court\)\{toast\('当前订场用户数据未加载，请刷新后重试','warn'\);return;\}/, 'membership entry should not silently fail when court data is missing');
assert.match(html, /function effectiveMembershipBenefitSource/, 'membership summary should treat empty snapshots as missing and keep falling back');
assert.match(html, /effectiveMembershipBenefitSource\(order\?\.benefitSnapshot,order,order\?\.planBenefitTemplateSnapshot,plan\)/, 'membership order summary should fall back when the stored snapshot is an empty object');
assert.match(html, /const planCount=parseInt\(planSnap\?\.\[item\.code\]\?\.count\)\|\|0;/, 'membership purchase list should compare current order total against plan base count');
assert.match(html, /const benefits=benefitRows\.length\?benefitRows\.map\(b=>`\$\{b\.label\} \$\{b\.remaining\}\/\$\{b\.total\}`\)\.join\('；'\):'—';/, 'membership account list should show remaining\/total benefit counts');
assert.match(html, /<thead style="font-size:10px"/, 'membership tables should use 10px table header size');
assert.match(html, /<tbody style="font-size:12px"/, 'membership tables should use 12px body size');
assert.doesNotMatch(html, /async function saveMembershipOrder[\s\S]*?await loadAll\(\)[\s\S]*?function openMembershipBenefitModal/, 'membership order save should avoid full reload to reduce waiting time');
assert.match(html, /if\(Date\.now\(\)-lastDataSyncAt>60000\)syncAllQuietly\(\);/, 'background sync should not refetch full data too aggressively');
assert.match(html, /setInterval\(syncAllQuietly,180000\);/, 'background sync interval should be reduced to avoid overloading save flows');
assert.match(html, /membershipBenefitCourtFilter/, 'membership benefit page should support filtering by court user');
assert.match(html, /赠送权益批次 = 每次购买送了什么、还剩多少、何时到期/, 'membership benefit page should explain batch table meaning');
assert.match(html, /权益流水 = 后来用了什么、补了什么、为什么变动/, 'membership benefit page should explain ledger table meaning');
assert.match(html, /时间[\s\S]*订场用户[\s\S]*购买批次[\s\S]*权益[\s\S]*变动[\s\S]*动作[\s\S]*原因/, 'membership benefit ledger page should keep audit columns only');
assert.doesNotMatch(html, /请选择权益账户，排课必须绑定课包权益/, 'schedule form should not hard-block saving when no entitlement is selected');

console.log('membership view tests passed');
