const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: html } = require('./helpers/read-index-bundle');

const pagesCss = fs.readFileSync(path.join(__dirname, '../public/assets/styles/pages.css'), 'utf8');
function fnBody(name) {
  const start = html.indexOf(`function ${name}`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next === -1 ? html.length : next);
}

assert.match(html, /goPage\('memberships',this\)[\s\S]*?会员管理/, 'sidebar should add membership management entry');
assert.match(html, /goPage\('membership-plans',this\)[\s\S]*?会员方案/, 'sidebar should add membership plan entry');
assert.match(html, /id="page-memberships"/, 'should have memberships page section');
assert.match(html, /id="page-membership-plans"/, 'should have dedicated membership plans page section');
assert.match(html, /id="page-membership-plans"[\s\S]*class="tms-toolbar"/, 'membership plan page should use the court-style toolbar');
assert.match(html, /id="page-membership-plans"[\s\S]*class="tms-table-card"[\s\S]*class="tms-table-wrapper"[\s\S]*class="tms-table"/, 'membership plan page should use the court-style table shell');
assert.match(pagesCss, /#page-membership-plans \.tms-table th\.tms-sticky-l[\s\S]*left:0/s, 'membership plan table should freeze the left name column');
assert.match(pagesCss, /#page-membership-plans \.tms-table td\.tms-sticky-r[\s\S]*right:0/s, 'membership plan table should keep the action column fixed on the right');
assert.doesNotMatch(html, /membershipTabOrders|membershipTabAccounts|membershipTabBenefits/, 'membership page should no longer use tabs');
assert.match(html, /查看购买记录[\s\S]*查看权益总流水/, 'membership page should expose audit links near the main actions');
assert.doesNotMatch(html, /page-memberships[\s\S]*方案配置/, 'membership management page should remove the scheme config shortcut');
assert.match(html, /id="membershipStatsRow"/, 'membership management page should expose summary stat cards');
assert.match(html, /function renderMembershipStats/, 'membership management page should compute summary stat cards');
assert.match(html, /会员数[\s\S]*订场次数[\s\S]*总收入金额[\s\S]*总余额/, 'membership summary should show booking count instead of purchase count');
assert.match(html, /id="page-memberships"[\s\S]*class="tms-toolbar"/, 'membership management page should use the court-style toolbar');
assert.match(html, /id="page-memberships"[\s\S]*class="tms-table-card"[\s\S]*class="tms-table-wrapper"[\s\S]*class="tms-table"/, 'membership management page should use the court-style table shell');
assert.match(html, /id="membershipSearch"[\s\S]*placeholder="搜索会员姓名、手机号或方案"/, 'membership management search should use the new unified copy');
assert.match(html, /id="page-membership-orders"[\s\S]*返回会员管理[\s\S]*会员购买记录/, 'membership purchase records should be a standalone page with a back entry');
assert.match(html, /id="page-membership-ledger"[\s\S]*返回会员管理[\s\S]*会员权益流水/, 'membership benefit ledger should be a standalone page with a back entry');

assert.match(html, /let courts=\[\],students=\[\],products=\[\],packages=\[\],purchases=\[\],entitlements=\[\],entitlementLedger=\[\],financialLedger=\[\],membershipPlans=\[\],membershipAccounts=\[\],membershipOrders=\[\],membershipBenefitLedger=\[\],membershipAccountEvents=\[\]/, 'frontend state should load membership data separately');
assert.match(html, /membershipPlans=Array\.isArray\(data\?\.membershipPlans\)\?data\.membershipPlans:\[\]/, 'load-all should store membership plans');
assert.match(html, /membershipAccounts=Array\.isArray\(data\?\.membershipAccounts\)\?data\.membershipAccounts:\[\]/, 'load-all should store membership accounts');
assert.match(html, /membershipOrders=Array\.isArray\(data\?\.membershipOrders\)\?data\.membershipOrders:\[\]/, 'load-all should store membership orders');
assert.match(html, /membershipBenefitLedger=Array\.isArray\(data\?\.membershipBenefitLedger\)\?data\.membershipBenefitLedger:\[\]/, 'load-all should store membership benefit ledger');

assert.match(html, /账户类型[\s\S]*当前会员[\s\S]*会员状态[\s\S]*当前折扣[\s\S]*会员到期/, 'courts table should show membership status columns');
assert.match(html, /function courtMembershipSummary/, 'courts page should compute membership summaries');
assert.match(html, /查看账户/, 'courts table should expose dedicated membership account entry');
assert.match(html, /编辑资料/, 'courts table should keep profile editing entry');
assert.match(html, /function openCourtMembershipPanel/, 'membership actions should move into dedicated account panel');
assert.match(html, /function courtMembershipPanelHtml/, 'membership account should render through dedicated panel html');
assert.match(html, /当前状态[\s\S]*当前权益[\s\S]*最近开卡[\s\S]*操作/, 'membership account panel should keep one clear rights section and recent purchase context');
assert.doesNotMatch(html, /余额来自 courts\.history，仅展示不可直接修改/, 'membership account panel should not expose backend wording');
assert.match(html, /余额由充值和消费自动计算，不能在这里手动改/, 'membership account panel should explain readonly balance in user wording');
assert.match(html, /个性化调整|标准权益/, 'membership account panel should call out customized rights');
assert.doesNotMatch(html, /当前可用权益[\s\S]*权益批次[\s\S]*最近购买记录[\s\S]*本次成交权益/, 'membership account panel should not repeat the same rights three times');
assert.match(html, /消耗权益[\s\S]*补发权益[\s\S]*查看流水/, 'membership account panel should expose structured benefit actions');
assert.match(html, /function courtMembershipBenefitRowsHtml/, 'membership account panel should render benefit rows');
assert.match(html, /function membershipBenefitBatchCardsHtml/, 'membership account panel should render benefit batches by order');
assert.match(html, /购买日期[\s\S]*方案名[\s\S]*批次到期/, 'membership batches should show purchase date, plan and expiry');
assert.match(html, /function membershipActionVisibility/, 'membership account panel should compute action visibility by status');
assert.match(html, /if\(\['voided','cleared'\]\.includes\(account\.status\)\)return \{reopen:true,ledger:true\}/, 'reopen should only be available for voided or cleared accounts');
assert.match(html, /已作废[\s\S]*折扣失效[\s\S]*权益不可再使用/, 'voided account panel should explain disabled discount and benefits');
assert.match(html, /重新开卡[\s\S]*查看流水/, 'voided or cleared accounts should keep reopen and ledger only');
assert.match(html, /if\(\['voided','cleared'\]\.includes\(account\?\.status\)\)return \[\]/, 'voided or cleared accounts should stop exposing available rights');
assert.match(html, /function openMembershipBenefitActionModal/, 'benefit actions should use dedicated modal');
assert.match(html, /function membershipBenefitConsumePreview/, 'benefit consume modal should build batch preview');
assert.match(html, /当前总剩余[\s\S]*优先扣减批次/, 'benefit consume modal should explain batch allocation');
assert.match(html, /如果当前批次不足，将继续扣减下一批/, 'benefit consume modal should explain cross-batch deduction');
assert.match(html, /本次补发会记入所选购买批次的权益调整，不会生成新的购买记录/, 'supplement modal should explain existing-batch attribution');
assert.match(html, /function openMembershipBenefitHistoryModal/, 'benefit history should have dedicated modal');
assert.match(html, /查看明细/, 'benefit card should use shorter history label');
assert.match(html, /查看全部权益流水/, 'court detail should provide all-benefit history entry for the current user');
assert.match(html, /function openCourtMembershipLedgerModal/, 'court detail should support all-benefit history modal');
assert.match(html, /setCourtModalFrame\('查看全部权益流水'[\s\S]*modal-wide/, 'all-benefit ledger should use the wide court modal shell');
assert.match(html, /membershipBenefitLedger\.filter\(l=>l\.membershipAccountId===account\.id&&l\.benefitCode===benefitCode&&l\.action!=='grant'\)/, 'benefit history should hide grant rows because purchase records already carry the issuance source');
assert.match(html, /membershipBenefitLedger\.filter\(l=>l\.membershipAccountId===account\.id&&l\.action!=='grant'\)/, 'all-benefit history should hide grant rows and focus on actual changes');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','consume'\)/, 'court detail shortcut actions should not hardcode ballMachine consume');
assert.doesNotMatch(html, /openMembershipBenefitActionModal\('\$\{court\.id\}','ballMachine','supplement'\)/, 'court detail shortcut actions should not hardcode ballMachine supplement');
assert.doesNotMatch(html, /openMembershipBenefitHistoryModal\('\$\{court\.id\}','ballMachine'\)/, 'court detail shortcut actions should not hardcode ballMachine history');

assert.match(html, /function studentMembershipSummaryHtml/, 'student detail should render linked court membership summary');
assert.match(html, /关联订场账户会员摘要/, 'student detail should label linked membership summary');
assert.match(html, /大师公开课[\s\S]*穿线免手工费[\s\S]*发球机免费[\s\S]*国家二级运动员陪打[\s\S]*指定教练陪打/, 'membership plan form should expose structured benefit fields');
assert.match(html, /余额有效期按支付日期起算 12 个月/, 'membership purchase flow should surface balance validity rule based on pay date');
assert.match(html, /系统创建日期只用于留痕，不影响会员有效期/, 'membership purchase flow should explain created time does not affect validity');
assert.match(html, /若到期时仍有余额，可自动进入延续期，最长至 24 个月/, 'membership purchase flow should surface extended validity rule');
assert.match(html, /低于原合规档位续充时，余额有效期不会重置/, 'membership purchase flow should warn when low-tier renewal does not reset validity');
assert.match(html, /余额由充值和消费自动计算，不能在这里手动改/, 'membership views should explain readonly balance in user wording');
assert.match(html, /每批赠送权益有效期 12 个月/, 'membership purchase flow should surface benefit batch validity rule');
assert.match(html, /function membershipOrderPreview/, 'membership order modal should build preview data');
assert.match(html, /function openMembershipOrderModal\(courtId,mode='renew'\)/, 'membership order modal should support first open renew and reopen modes');
assert.match(html, /本次会发生什么/, 'membership order modal should show change preview first');
assert.match(html, /是否重置有效期[\s\S]*折扣变化[\s\S]*原有权益保留[\s\S]*本次新增权益/, 'membership order preview should explain the main impact clearly');
assert.match(html, /<details[\s\S]*本次额外赠送/, 'one-time adjustments should still exist but be collapsed by default');
assert.match(html, /我了解折扣和有效期变化，确认续充/, 'low-tier renewal should use stronger confirm wording');
assert.match(html, /function membershipOrderDraftFromPlan/, 'membership order modal should derive one-time benefit draft from selected plan');
assert.match(html, /function membershipStepperHtml/, 'membership forms should use stepper helper');
assert.match(html, /function membershipPlanPreviewHtml/, 'membership plan form should render realtime preview');
assert.match(html, /function refreshMembershipPlanPreview/, 'membership plan form should refresh preview on input');
assert.match(html, /售卖开始日期[\s\S]*售卖结束日期[\s\S]*方案状态/, 'membership plan form should expose sale window and plan status fields');
assert.match(html, /草稿[\s\S]*上架[\s\S]*停售/, 'membership plan form should expose draft, active and inactive statuses');
assert.match(html, /saleStartDate[\s\S]*saleEndDate/, 'membership plan save and rendering should include sale window fields');
assert.doesNotMatch(html, /id="mp_discount"[^>]*value="1"/, 'membership plan discount should not force default value 1 in html');
assert.doesNotMatch(html, /例如 8 折填 0\.8/, 'membership plan discount should not ask operators to type decimal discount');
assert.match(html, /mp_discount/, 'membership plan discount should use explicit option selection');
assert.doesNotMatch(html, /id="mp_publicLesson"[^>]*value="0"/, 'membership plan benefit inputs should not force default zero in html');
assert.doesNotMatch(html, /id="mo_publicLesson"[^>]*value="0"/, 'membership order adjustment inputs should not force default zero in html');
assert.match(html, /本次额外赠送/, 'membership order modal should allow one-time benefit adjustments');
assert.match(html, /大师公开课本次调整[\s\S]*穿线免手工费本次调整[\s\S]*发球机免费本次调整[\s\S]*国家二级运动员陪打本次调整[\s\S]*指定教练陪打本次调整/, 'membership order modal should expose one-time benefit adjustment fields');
assert.match(html, /指定教练范围本次调整/, 'membership order modal should expose one-time designated coach override');
assert.match(html, /选择指定教练/, 'membership plan and order forms should use coach-linked designated coach selector');
assert.match(html, /function membershipCoachSelectorHtml/, 'designated coach selection should be rendered by helper');
assert.match(html, /coaches\.map/, 'designated coach selector should be linked to coach records');
assert.match(html, /function membershipOrderBenefitSummaryHtml/, 'membership purchase list should render readable benefit batch summary');
assert.match(html, /额外赠送/, 'membership purchase list should show one-off extra benefit adjustments');
assert.match(html, /function renderMembershipOrdersAuditPage/, 'membership page should render purchase audit as a standalone page');
assert.match(html, /function renderMembershipLedgerAuditPage/, 'membership page should render ledger audit as a standalone page');
assert.match(html, /onclick="goPage\('membership-orders'\)"/, 'membership management purchase audit entry should navigate to standalone page');
assert.match(html, /onclick="goPage\('membership-ledger'\)"/, 'membership management ledger audit entry should navigate to standalone page');
assert.match(html, /membershipBenefitLedger\.filter\(l=>l\.action!=='grant'&&searchHit/, 'global benefit audit should hide grant rows');
assert.match(html, /购买日期[\s\S]*订场用户[\s\S]*会员方案[\s\S]*充值[\s\S]*赠送金额[\s\S]*折扣[\s\S]*是否重置有效期[\s\S]*当次权益摘要[\s\S]*状态/, 'membership purchase audit should keep reduced audit fields');
assert.match(html, /时间[\s\S]*订场用户[\s\S]*购买批次[\s\S]*权益[\s\S]*变动[\s\S]*动作[\s\S]*原因/, 'membership ledger audit should keep audit columns only');
assert.match(html, /此页面仅用于审计与追溯，不用于日常操作/, 'audit modal should explain read-only positioning');
assert.match(html, /权益有效期固定 12 个月[\s\S]*余额最长按当前系统规则至 24 个月/, 'membership plan form should explain fixed validity rules');
assert.match(html, /可用权益/, 'membership account list should expose benefit summary');
assert.match(html, /查看账户/, 'membership account list should expose account detail entry');
assert.match(html, /function membershipDisplayStatus/, 'frontend should compute display status labels');
assert.match(html, /function membershipStatusTagMeta/, 'frontend should compute membership status tag styles');
assert.match(html, /function membershipValidityHint/, 'frontend should compute validity hint text');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*开通会员/, 'court edit modal should not include membership open action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*续充会员/, 'court edit modal should not include membership renew action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*消耗 1 次/, 'court edit modal should not include benefit consume action');
assert.doesNotMatch(html, /function openCourtModal[\s\S]*补发/, 'court edit modal should not include benefit supplement action');
assert.match(html, /function normalizeCurrentPageForRole/, 'frontend should normalize landing page by role before rendering');
assert.match(html, /function renderRoleShell/, 'frontend should centralize role shell rendering');
assert.match(html, /applyLoadedData[\s\S]*normalizeCurrentPageForRole\(\);[\s\S]*renderRoleShell\(\);/, 'load-all should re-sync shell after user role changes');
assert.match(html, /function clearLoadedData/, 'frontend should clear stale data when login\/load-all fails');
assert.match(html, /let lastDataSyncAt=0,isSyncingAll=false,dataRequestVersion=0;/, 'frontend should track request version to ignore stale load-all responses');
assert.match(html, /const requestVersion=\+\+dataRequestVersion;[\s\S]*if\(requestVersion!==dataRequestVersion\)return;/, 'load-all and background sync should ignore stale responses from older sessions');
assert.match(html, /clearLoadedData\(\);[\s\S]*buildCampusTabs\(\);[\s\S]*renderAll\(\);[\s\S]*toast\('加载失败：'/, 'load-all failure should clear stale data and stale campus tabs before showing error');
assert.match(html, /if\(!court\)\{toast\('当前订场用户数据未加载，请刷新后重试','warn'\);return;\}/, 'membership entry should not silently fail when court data is missing');
assert.match(html, /function effectiveMembershipBenefitSource/, 'membership summary should treat empty snapshots as missing and keep falling back');
assert.match(html, /function membershipOrderEffectiveBenefitSource/, 'frontend should centralize deal snapshot priority for benefit display');
assert.doesNotMatch(html, /effectiveMembershipBenefitSource\(order\?\.benefitSnapshot,order,order\?\.planBenefitTemplateSnapshot,plan\)/, 'frontend benefit display should not refill omitted rights from the plan after a deal snapshot exists');
assert.match(html, /const planCount=parseInt\(planSnap\?\.\[item\.code\]\?\.count\)\|\|0;/, 'membership purchase list should compare current order total against plan base count');
assert.match(html, /const benefits=benefitRows\.length\?benefitRows\.map\(b=>`\$\{b\.label\} \$\{b\.remaining\}\/\$\{b\.total\}`\)\.join\('；'\):'—';/, 'membership account list should show remaining\/total benefit counts');
assert.match(html, /function resetModalActions\(\)/, 'membership modals should clear stale footer actions before using body-level action areas');
assert.match(html, /function openMembershipOrderModal/, 'membership order modal should remain available');
assert.match(html, /function openMembershipBenefitActionModal/, 'benefit action modal should remain available');
assert.match(html, /setCourtModalFrame\(`\$\{court\.name\} · 会员账户`,courtMembershipPanelHtml\(court\),'',/, 'membership account panel should not append an extra close footer');
assert.match(html, /modal-member/, 'membership account panel should use a wider dedicated modal shell');
assert.match(html, /售卖时间[\s\S]*方案状态[\s\S]*操作/, 'membership plan list should show sale window and plan status columns');
assert.match(html, /tms-action-link[\s\S]*(删除[\s\S]*上架[\s\S]*编辑|停售[\s\S]*编辑)/, 'membership plan list should use the requested action order');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:500px;max-width:none;color:#A3968F"/, 'membership plan benefits should show full text when the table scrolls horizontally');
assert.match(html, /if\(pg==='membership-orders'\)renderMembershipOrdersAuditPage\(\);/, 'page router should render standalone purchase audit page');
assert.match(html, /if\(pg==='membership-ledger'\)renderMembershipLedgerAuditPage\(\);/, 'page router should render standalone ledger audit page');
assert.match(html, /'membership-orders'[\s\S]*'membership-ledger'/, 'admin pages should include membership audit pages');
assert.doesNotMatch(html, /async function saveMembershipOrder[\s\S]*?await loadAll\(\)[\s\S]*?function openMembershipBenefitModal/, 'membership order save should avoid full reload to reduce waiting time');
assert.match(html, /if\(Date\.now\(\)-lastDataSyncAt>60000\)syncAllQuietly\(\);/, 'background sync should not refetch full data too aggressively');
assert.match(html, /setInterval\(syncAllQuietly,180000\);/, 'background sync interval should be reduced to avoid overloading save flows');
assert.doesNotMatch(html, /membershipBenefitCourtFilter/, 'membership management page should remove the global benefit batch filter');
assert.doesNotMatch(html, /赠送权益批次 = 每次购买送了什么、还剩多少、何时到期/, 'membership management page should no longer expose global benefit batch explanation');
assert.doesNotMatch(html, /请选择权益账户，排课必须绑定课包权益/, 'schedule form should not hard-block saving when no entitlement is selected');
assert.match(html, /会员状态<\/th>[\s\S]*订场次数<\/th>[\s\S]*余额有效期<\/th>[\s\S]*清零时间<\/th>/, 'membership management list should show booking count before validity columns');
assert.match(html, /function membershipBookingCount\(/, 'membership management should expose a helper to count stored-value bookings');
assert.match(fnBody('membershipBookingCount'), /h\.type==='消费'&&String\(h\.payMethod\|\|''\)\.trim\(\)==='储值扣款'&&String\(h\.category\|\|''\)\.includes\('订场'\)/, 'membership booking count should only include stored-value booking consumption');
assert.match(html, /class="tms-action-link tms-action-link-strong" style="color:#C06031" onclick="goPage\('membership-orders'\)"/, 'membership management purchase audit entry should use visible accent color');
assert.match(html, /class="tms-action-link tms-action-link-strong" style="color:#C06031" onclick="goPage\('membership-ledger'\)"/, 'membership management ledger audit entry should use visible accent color');
assert.match(pagesCss, /#page-memberships \.tms-toolbar-right \.tms-action-link-strong[\s\S]*#FEF3C7/s, 'membership audit entries should be readable on the brown background');
assert.match(html, /const statusMeta=membershipStatusTagMeta\(a\);/, 'membership management rows should derive status tag metadata');
assert.match(html, /function membershipVisibleCourt/, 'membership management should ignore deleted or archived court users');
assert.match(fnBody('renderMemberships'), /courts\.filter\(court=>isActiveCourtRecord\(court\)\)\.map/, 'membership management should build rows from active court users only');
assert.match(html, /function isActiveCourtRecord\(/, 'frontend should centralize active court filtering');
assert.match(fnBody('isActiveCourtRecord'), /status!=='inactive'&&status!=='deleted'&&!court\?\.deletedAt&&!court\?\.mergedIntoCourtId/, 'active court filtering should exclude hidden, deleted and merged users');
assert.match(fnBody('renderMemberships'), /openCourtMembershipPanel\('\$\{court\.id\}'\)/, 'membership account action should open the account for the visible row court');
assert.match(html, /const statusTagMeta=membershipStatusTagMeta\(m\.status\);/, 'court rows should derive status tag metadata');
assert.match(html, /memberLabel:'-',tierLabel:'-',status:membershipDisplayStatus\(account\),discount:'-',validUntil:'-'/, 'voided or cleared membership summaries should clear benefit display in court list');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:320px;color:#A3968F"/, 'membership management benefits should use the same remark color as membership plan notes');
assert.match(html, /style="white-space:normal;line-height:1\.55;min-width:500px;max-width:none;color:#A3968F"/, 'membership plan benefits should use the remark color while staying fully visible');
assert.match(html, /会员账户<\/span>/, 'court user list should label the membership account action clearly');
assert.match(html, /function openMembershipBenefitPickerModal/, 'generic consume and supplement actions should let operators choose a benefit type');
assert.match(html, /id="membershipBenefitSaveBtn"[\s\S]*保存中/, 'benefit save action should show a submitting state');
assert.match(html, /会员管理[\s\S]*\/[\s\S]*会员购买记录/, 'purchase audit page should use breadcrumb-style navigation');
assert.match(html, /会员管理[\s\S]*\/[\s\S]*会员权益流水/, 'ledger audit page should use breadcrumb-style navigation');
assert.match(html, /tms-audit-note/, 'audit pages should use a slim read-only note');
assert.match(html, /支付日期<\/th>[\s\S]*录入时间<\/th>[\s\S]*订场用户/, 'membership order audit should show pay date and recorded time columns');
assert.match(html, /会员方案 \*[\s\S]*系统价格[\s\S]*实收\/充值金额[\s\S]*改价原因/, 'membership order modal should expose system price and override reason fields');
assert.match(html, /支付日期<\/th>[\s\S]*系统价[\s\S]*成交价[\s\S]*改价原因/, 'membership order audit should show price snapshot columns');
assert.match(html, /当前会员[\s\S]*courtMembershipTierLabel\(a\)/, 'membership management should show the member tier like the court user current-member column');
assert.match(html, /formatMembershipLedgerTime/, 'membership ledger audit should format readable date and time');
assert.match(html, /membershipLedgerActionText/, 'membership ledger audit should translate backend actions to Chinese');
assert.match(html, /membershipLedgerOperatorText/, 'membership ledger audit should normalize operator account names');
assert.match(html, /renderCourtCellText\(membershipLedgerOperatorText\(l\.operator\)\)/, 'membership ledger audit should render the normalized operator account name');
assert.match(html, /操作账号/, 'membership ledger audit should show operator account');
assert.match(html, /已消耗/, 'membership account rights should show consumed count');
assert.match(html, /作废信息[\s\S]*作废时间[\s\S]*作废人[\s\S]*作废原因/, 'membership account panel should show voiding audit information');
assert.match(pagesCss, /membership-rights-row\{display:grid;grid-template-columns:minmax\(0,1fr\) 110px 110px 110px 140px/, 'membership rights should keep expiry and counts in one row');
assert.match(fnBody('membershipBenefitSummaryForOrder'), /const positiveDelta=.*?delta\)\|\|0\)>0[\s\S]*const negativeDelta=.*?delta\)\|\|0\)<0[\s\S]*const total=\(item\.total\|\|0\)\+positiveDelta[\s\S]*remaining:expired\?0:Math\.max\(0,total\+negativeDelta\)/, 'frontend benefit summary should add supplements to both total and remaining');

console.log('membership view tests passed');
