const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', 'wechat-miniprogram', 'miniprogram');
const appJson = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));
const appJs = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const matchesJs = fs.readFileSync(path.join(root, 'pages', 'matches', 'index.js'), 'utf8');
const matchesWxml = fs.readFileSync(path.join(root, 'pages', 'matches', 'index.wxml'), 'utf8');
const tabBarWxml = fs.readFileSync(path.join(root, 'custom-tab-bar', 'index.wxml'), 'utf8');
const tabBarJs = fs.readFileSync(path.join(root, 'custom-tab-bar', 'index.js'), 'utf8');
const indexJs = fs.readFileSync(path.join(root, 'pages', 'index', 'index.js'), 'utf8');
const indexWxml = fs.readFileSync(path.join(root, 'pages', 'index', 'index.wxml'), 'utf8');
const profileJs = fs.readFileSync(path.join(root, 'pages', 'profile', 'index.js'), 'utf8');
const profileWxml = fs.readFileSync(path.join(root, 'pages', 'profile', 'index.wxml'), 'utf8');
const createJs = fs.readFileSync(path.join(root, 'pages', 'match-create', 'index.js'), 'utf8');
const createWxml = fs.readFileSync(path.join(root, 'pages', 'match-create', 'index.wxml'), 'utf8');
const detailJs = fs.readFileSync(path.join(root, 'pages', 'match-detail', 'index.js'), 'utf8');
const myMatchesJs = fs.readFileSync(path.join(root, 'pages', 'my-matches', 'index.js'), 'utf8');

assert.ok(!appJson.pages.includes('pages/matches/index'), 'coach mini program shell should not register the match home page');
assert.ok(!appJson.pages.includes('pages/match-detail/index'), 'coach mini program shell should not register the match detail page');
assert.ok(!appJson.pages.includes('pages/my-matches/index'), 'coach mini program shell should not register the my matches page');
assert.ok(!appJson.pages.includes('pages/profile/index'), 'coach mini program shell should not register the match profile page');
assert.ok(!appJson.pages.includes('pages/match-create/index'), 'coach mini program shell should not register the match create page');
assert.strictEqual(appJson.pages[0], 'pages/index/index', 'coach mini program shell should default into the coach login page');
assert.match(appJs, /currentUser/, 'mini program app should restore the original match session globals');
assert.match(indexWxml, /FLOWTENNIS · 管理系统/, 'coach page should stay separate');
assert.doesNotMatch(indexWxml, /微信进入约球/, 'coach page should not expose the match login entry');
assert.doesNotMatch(indexJs, /loginMatchWithWechat|enterMatchMini/, 'coach page should not own match login logic');
assert.doesNotMatch(tabBarWxml, /约球|我的|match-create|matches\/index|profile\/index/, 'coach mini program shell should not keep match labels in the custom tab bar files');
assert.doesNotMatch(tabBarJs, /约球|我的|match-create|matches\/index|profile\/index/, 'coach mini program shell should not keep match routing in the custom tab bar logic');
assert.match(matchesWxml, /今晚去哪儿/, 'match home should restore the original hero copy');
assert.match(matchesWxml, /立即报名/, 'match home should restore the original signup action');
assert.match(matchesJs, /listMatches/, 'match home should load match list data');
assert.match(matchesJs, /registerMatch/, 'match home should register matches after login and phone auth are satisfied');
assert.match(matchesJs, /requireLogin/, 'match home should gate signup behind login when needed');
assert.match(matchesJs, /updateMatchPhoneByCode/, 'match home should still support phone bind during signup');
assert.doesNotMatch(matchesJs, /请先登录后查看约球列表/, 'match home should no longer block guest users from browsing the home list');
assert.match(profileJs, /ensureInteractiveLogin/, 'profile page should keep the original login entry flow');
assert.match(profileJs, /updateMatchPhoneByCode/, 'profile page should bind phone through phone-code endpoint');
assert.match(profileWxml, /授权手机号|重新授权手机号/, 'profile page should expose phone authorization entry');
assert.match(profileWxml, /查看我的约球/, 'profile page should restore the original my matches entry');
assert.match(profileJs, /createAccessText/, 'profile page should track publish permission state after phone bind and profile refresh');
assert.match(createJs, /submitMatchWithPhone/, 'match create page should keep the original phone-gated submit flow');
assert.match(createWxml, /发布约球/, 'match create page should restore the original publish CTA');
assert.match(detailJs, /registerWithPhone/, 'match detail page should keep phone gating for signup');
assert.match(myMatchesJs, /requireLogin/, 'my matches page should stay behind login');
assert.match(createJs, /createMatch/, 'match create page should call create match api');

console.log('miniprogram match ops closure tests passed');
