const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '../public/assets/scripts/core/state.js'), 'utf8');

assert.match(source, /students:\['campuses','students'\]/, 'students page should only block on the datasets needed to paint the list immediately');
assert.match(source, /products:\['products','classes'\]/, 'products page should only block on products and classes after plans retirement');
assert.doesNotMatch(source, /products:\['products','classes','plans'\]/, 'products page should no longer block on the retired plans dataset');
assert.match(source, /plans:\[\]/, 'plans page should open shell immediately and load data in background');
assert.match(source, /packages:\[\]/, 'packages page should open shell immediately and load data in background');
assert.match(source, /purchases:\[\]/, 'purchases page should open shell immediately and load data in background');
assert.match(source, /finance:\[\]/, 'finance center should open shell immediately and load aggregated data in background');
assert.match(source, /courts:\[\]/, 'courts page should open shell immediately and load data in background');
assert.match(source, /memberships:\[\]/, 'memberships page should open shell immediately and load data in background');
assert.match(source, /workbench:\[\]/, 'coach workbench should open immediately and load data in background');
assert.match(source, /myschedule:\[\]/, 'coach schedule should open immediately and load data in background');
assert.match(source, /mystudents:\[\]/, 'coach students should open immediately and load data in background');
assert.match(source, /myclasses:\[\]/, 'coach classes should open immediately and load data in background');
assert.match(source, /const PAGE_DATA_BACKGROUND_REQUIREMENTS=\{[\s\S]*students:\['entitlements','entitlementLedger','classes','schedule','feedbacks','courts'\][\s\S]*plans:\[\][\s\S]*packages:\['packages'\][\s\S]*purchases:\['purchasesPage'\][\s\S]*finance:\['financePage'\][\s\S]*courts:\['courtsPage'\][\s\S]*memberships:\['membershipsPage'\][\s\S]*workbench:\['workbenchPage'\][\s\S]*myschedule:\['campuses','students','classes','schedule','feedbacks'\][\s\S]*mystudents:\['campuses','students','classes','schedule','feedbacks','entitlements'\][\s\S]*myclasses:\['students','classes'\]/, 'student page background loading should stop depending on products for display-only fallback');
assert.doesNotMatch(source, /plansPage:\(\)=>apiCall\('GET','\/page-data\/plans'\)/, 'plans page should no longer request a dedicated aggregated endpoint');
assert.match(source, /purchasesPage:\(\)=>apiCall\('GET','\/page-data\/purchases'\)/, 'purchases page should use a dedicated aggregated endpoint');
assert.match(source, /financePage:\(\)=>apiCall\('GET','\/page-data\/finance'\)/, 'finance center should use a dedicated aggregated endpoint');
assert.match(source, /courtsPage:\(\)=>apiCall\('GET','\/page-data\/courts'\)/, 'courts page should use a dedicated aggregated endpoint');
assert.match(source, /membershipsPage:\(\)=>apiCall\('GET','\/page-data\/memberships'\)/, 'memberships page should use a dedicated aggregated endpoint');
assert.match(source, /workbenchPage:\(\)=>apiCall\('GET','\/page-data\/workbench'\)/, 'coach workbench should use a dedicated aggregated endpoint');
assert.match(source, /Promise\.allSettled\(names\.map/, 'background loading should fetch page datasets in parallel');
assert.doesNotMatch(source, /if\(name==='plansPage'\)\{/, 'plans page aggregate hydration branch should be removed with the retired endpoint');
assert.match(source, /if\(name==='purchasesPage'\)\{[\s\S]*setDatasetValue\('purchases',data\.purchases\|\|\[\]\);[\s\S]*setDatasetValue\('packages',data\.packages\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('entitlements',data\.entitlements\|\|\[\]\);/, 'purchases page aggregate loader should hydrate all dependent datasets from one response');
assert.match(source, /if\(name==='financePage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('schedule',data\.schedule\|\|\[\]\);[\s\S]*setDatasetValue\('entitlements',data\.entitlements\|\|\[\]\);[\s\S]*setDatasetValue\('entitlementLedger',data\.entitlementLedger\|\|\[\]\);[\s\S]*setDatasetValue\('coaches',data\.coaches\|\|\[\]\);[\s\S]*setDatasetValue\('products',data\.products\|\|\[\]\);[\s\S]*setDatasetValue\('purchases',data\.purchases\|\|\[\]\);[\s\S]*setDatasetValue\('packages',data\.packages\|\|\[\]\);/, 'finance aggregate loader should hydrate report dependencies from one response');
assert.match(source, /if\(name==='courtsPage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('courts',data\.courts\|\|\[\]\);[\s\S]*setDatasetValue\('membershipAccounts',data\.membershipAccounts\|\|\[\]\);[\s\S]*setDatasetValue\('coaches',data\.coaches\|\|\[\]\);[\s\S]*setDatasetValue\('pricePlans',data\.pricePlans\|\|\[\]\);/, 'courts page aggregate loader should hydrate all dependent datasets from one response');
assert.match(source, /if\(name==='membershipsPage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('courts',data\.courts\|\|\[\]\);[\s\S]*setDatasetValue\('membershipAccounts',data\.membershipAccounts\|\|\[\]\);[\s\S]*setDatasetValue\('membershipOrders',data\.membershipOrders\|\|\[\]\);[\s\S]*setDatasetValue\('membershipBenefitLedger',data\.membershipBenefitLedger\|\|\[\]\);[\s\S]*setDatasetValue\('membershipAccountEvents',data\.membershipAccountEvents\|\|\[\]\);[\s\S]*setDatasetValue\('membershipPlans',data\.membershipPlans\|\|\[\]\);[\s\S]*setDatasetValue\('coaches',data\.coaches\|\|\[\]\);/, 'memberships page aggregate loader should hydrate all dependent datasets from one response');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*setDatasetValue\('campuses',data\.campuses\|\|\[\]\);[\s\S]*setDatasetValue\('students',data\.students\|\|\[\]\);[\s\S]*setDatasetValue\('classes',data\.classes\|\|\[\]\);[\s\S]*setDatasetValue\('schedule',data\.schedule\|\|\[\]\);[\s\S]*setDatasetValue\('feedbacks',data\.feedbacks\|\|\[\]\);/, 'workbench aggregate loader should hydrate coach homepage dependencies from one response');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*window\.coachWorkbenchStats=data\.stats\|\|\{/, 'workbench aggregate loader should keep the backend standard stats payload');
assert.match(source, /if\(name==='workbenchPage'\)\{[\s\S]*setDatasetValue\('schedule',data\.schedule\|\|\[\]\);/, 'workbench aggregate loader should still hydrate schedule rows from the aggregated payload');
assert.doesNotMatch(source, /if\(name==='workbenchPage'\)\{[\s\S]*setDatasetValue\('purchases',data\.purchases\|\|\[\]\);/, 'workbench aggregate loader should not hydrate the full purchases dataset just to render the coach homepage');
assert.match(source, /const DATA_CACHE_PREFIX='ft_dataset_cache_';/, 'state should persist the last successful datasets for refresh fallback');
assert.match(source, /function hydrateDatasetsFromCache\(\)/, 'state should hydrate cached datasets before network refresh');
assert.match(source, /function isDatasetCacheUsable\(name,data\)/, 'state should expose cache usability checks before hydrating cached datasets');
assert.match(source, /if\(name==='coaches'\)\{\s*return Array\.isArray\(data\)&&data\.some\(item=>String\(item\?\.id\|\|''\)\.trim\(\)\|\|String\(item\?\.name\|\|''\)\.trim\(\)\);\s*\}/, 'coaches cache should be ignored when it is empty or structurally blank');
assert.match(source, /GLOBAL_DATASET_NAMES\.forEach\(name=>\{[\s\S]*const cached=readDatasetCache\(name\);[\s\S]*if\(isDatasetCacheUsable\(name,cached\)\)setDatasetValue\(name,cached,\{persist:false\}\);[\s\S]*\}\);/, 'cache hydration should skip unusable coaches cache instead of marking it as already loaded');
assert.match(source, /function persistDatasetCache\(name,data\)/, 'state should cache every successful dataset load');
assert.doesNotMatch(source, /function persistDatasetCache\(name,data\)\{\s*return;\s*\}/, 'dataset cache persistence should not be disabled');
assert.doesNotMatch(source, /function readDatasetCache\(name\)\{\s*return null;\s*\}/, 'dataset cache reads should not be disabled');
assert.doesNotMatch(source, /plans:\(\)=>apiCall\('GET','\/plans'\)/, 'global dataset loaders should stop requesting the retired plans dataset');
assert.match(source, /const GLOBAL_DATASET_NAMES=Object\.keys\(DATASET_LOADERS\);/, 'state should keep a dedicated global dataset load list');
assert.doesNotMatch(source, /const GLOBAL_DATASET_NAMES=Object\.keys\(DATASET_LOADERS\)\.concat\('plans'\);/, 'global dataset load list should not append the retired plans dataset back in');
assert.match(source, /await ensureDatasetsByName\(GLOBAL_DATASET_NAMES,\{force:true\}\);/, 'load-all should refresh only the active global datasets');
assert.match(source, /const DATASETS_EXCLUDED_FROM_CACHE=new Set\(\['entitlementLedger'\]\);/, 'volatile entitlement ledger should stay network-only while normal lists use refresh cache');
assert.match(source, /const SENSITIVE_DATASETS_EXCLUDED_FROM_CACHE_IN_NON_PRODUCTION=new Set\(\[[\s\S]*'financialLedger'[\s\S]*'purchases'[\s\S]*'membershipAccounts'[\s\S]*'membershipOrders'[\s\S]*'membershipBenefitLedger'[\s\S]*'membershipAccountEvents'[\s\S]*\]\);/, 'preview and staging should refuse to persist the most sensitive finance datasets');
assert.match(source, /function datasetCacheKey\(name\)\{\s*return DATA_CACHE_PREFIX\+CLIENT_DATA_CACHE_SCOPE\+'_'\+\(currentUser\?\.id\|\|'anon'\)\+'_'\+name;\s*\}/, 'dataset cache keys should be isolated by runtime scope before the user id');
assert.match(source, /if\(isNonProductionRuntime\(\)&&pg==='finance'\)return \['financePage'\];/, 'preview and staging finance should wait for the fresh aggregated response instead of trusting old partial caches');
assert.match(source, /function missingRequiredDatasetsForPage\(pg\)/, 'state should be able to detect when the current page still lacks blocking datasets');
assert.match(source, /function missingInitialDatasetsForPage\(pg\)/, 'state should detect empty-shell pages waiting for their first background dataset');
assert.match(source, /function renderPageLoading\(pg\)/, 'state should render inline loading placeholders instead of empty pages');
assert.doesNotMatch(source, /renderBlockLoading\('coachOpsRevenueStats','财务汇总加载中\.\.\.'\)/, 'finance page should not render a duplicate top loading line above the revenue table');
assert.match(source, /if\(pageNeedsInlineLoading\(pg\)\)\{\s*renderPageLoading\(pg\);\s*return;\s*\}/, 'page rendering should show inline loading placeholders until the page has the datasets it needs');
assert.match(source, /const datasetLoadPromises=new Map\(\);/, 'state should de-duplicate concurrent dataset requests');
assert.match(source, /datasetLoadPromises\.has\(name\)/, 'dataset loading should reuse in-flight requests');
assert.match(source, /loadPageBackgroundDatasets\(pg,requestVersion,\{force\}\);/, 'page background loading should respect the current refresh mode instead of always forcing a full revalidation');
assert.match(source, /await loadPageDataAndRender\(currentPage,\{quiet:true,force:true\}\);/, 'explicit quiet sync should still force a revalidation when the app decides data is stale');

console.log('page data requirements tests passed');
