const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { appSource: source } = require('./helpers/read-index-bundle');
const styles = fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', 'styles', 'pages.css'), 'utf8');

function fnBody(name){
  const start = source.indexOf(`function ${name}(`);
  assert.notStrictEqual(start, -1, `${name} should exist`);
  const nextFunction = source.indexOf('\nfunction ', start + 1);
  const nextAsync = source.indexOf('\nasync function ', start + 1);
  const candidates = [nextFunction, nextAsync].filter(i => i !== -1);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next === -1 ? source.length : next);
}

assert.match(source, /function buildRepeatScheduleSeeds\(/, 'schedule page should expose a repeat schedule helper');
assert.match(fnBody('openScheduleModal'), /sch_repeatEnabled/, 'schedule modal should allow enabling repeat scheduling');
assert.match(fnBody('openScheduleModal'), /每周重复/, 'schedule modal should describe weekly repeat scheduling');
assert.match(fnBody('openScheduleModal'), /教练迟到免费/, 'schedule modal should support marking coach-late free lessons');
assert.match(fnBody('openScheduleModal'), /教练承担场地费/, 'schedule modal should capture coach late field fee');
assert.match(fnBody('scheduleSaveConfirmText'), /迟到免费/, 'schedule save confirm copy should show coach-late free status');
assert.match(fnBody('saveSchedule'), /buildRepeatScheduleSeeds\(/, 'saving schedules should fan out repeat seeds when enabled');
assert.match(fnBody('saveSchedule'), /coachLateFree/, 'saving schedules should persist coach late fields');
assert.match(fnBody('openScheduleDetail'), /教练迟到处理/, 'schedule detail should show coach late settlement info');
assert.match(source, /function scheduleLocationText\(/, 'schedule page should centralize location display');
assert.match(fnBody('openScheduleModal'), /地点类型[\s\S]*校区内[\s\S]*校区外/, 'schedule modal should support in-campus and off-campus lesson location types');
assert.match(fnBody('openScheduleModal'), /schedule-time-course-row[\s\S]*schedule-time-field[\s\S]*sch_courseType/, 'schedule modal should keep time controls compact beside course type');
assert.match(fnBody('openScheduleModal'), /schedule-location-row[\s\S]*sch_locationType[\s\S]*sch_ownLocationRow[\s\S]*sch_campus[\s\S]*sch_venue/, 'own campus location fields should sit on one row with location type');
assert.match(fnBody('openScheduleModal'), /schedule-location-row[\s\S]*sch_locationType[\s\S]*sch_externalLocationRow[\s\S]*sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external location fields should sit on one row with location type');
assert.match(fnBody('openScheduleModal'), /人和课程[\s\S]*关联班次[\s\S]*本次参与人[\s\S]*上课信息[\s\S]*上课日期与时间[\s\S]*课程类型[\s\S]*教练[\s\S]*消课节数[\s\S]*扣减课包[\s\S]*地点/, 'schedule modal should follow the simplified create/edit flow');
assert.match(fnBody('openScheduleModal'), /上课日期与时间[\s\S]*课程类型[\s\S]*每周重复/, 'weekly repeat should stay with lesson time settings');
assert.match(fnBody('openScheduleModal'), /sch_externalVenueName[\s\S]*sch_externalCourtName[\s\S]*sch_externalNotes/, 'external venue schedules should capture venue, court, and notes');
assert.doesNotMatch(fnBody('openScheduleModal'), /sch_externalAddress|地址/, 'external venue schedules should not ask for an address');
assert.match(fnBody('openScheduleModal'), /更多设置[\s\S]*教练迟到处理/, 'coach late fields should remain folded as advanced settings');
assert.doesNotMatch(fnBody('openScheduleModal'), /通知状态|确认状态|确认规则/, 'schedule modal should remove fake notification and confirmation fields');
assert.doesNotMatch(fnBody('scheduleSaveConfirmText'), /确认规则|确认截止|通知：/, 'schedule save confirm copy should not show fake notification rules');
assert.doesNotMatch(fnBody('openScheduleDetail'), /通知 \/ 确认|确认规则/, 'schedule detail should not show fake notification rules');
assert.match(fnBody('scheduleStatusLabel'), /已结束[\s\S]*已下课/, 'schedule ended status should display as 已下课');
assert.match(fnBody('renderSchedule'), /scheduleStatusLabel/, 'schedule list should render user-facing status text');
assert.match(source, /function openCoachLateSettlementModal\(/, 'schedule page should expose coach late settlement modal');
assert.match(source, /迟到月结/, 'schedule page should expose coach late monthly settlement entry');
assert.doesNotMatch(source, /id="page-schedule"[\s\S]*?openCoachLateSettlementModal\(\)[\s\S]*?id="page-coachops"/, 'late monthly settlement should not be a primary schedule-table action');
assert.match(source, /id="page-coachops"[\s\S]*?openCoachLateSettlementModal\(\)/, 'late monthly settlement entry should live in coach operations');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-summary/, 'late settlement modal should show a compact summary');
assert.match(fnBody('openCoachLateSettlementModal'), /迟到次数/, 'late settlement summary should include late count');
assert.match(fnBody('openCoachLateSettlementModal'), /迟到分钟/, 'late settlement summary should include late minutes');
assert.match(fnBody('openCoachLateSettlementModal'), /承担合计/, 'late settlement summary should include payable total');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-table/, 'late settlement modal should use a scoped compact table');
assert.match(fnBody('openCoachLateSettlementModal'), /late-settlement-empty/, 'late settlement modal should use a compact empty state');
assert.match(source, /const FEEDBACK_POSTER_TEMPLATES\s*=/, 'feedback poster should define fixed template configs');
assert.match(source, /blueGreenDiagonal[\s\S]*minimalDarkGreen[\s\S]*retroCourt[\s\S]*blueprintBlue[\s\S]*minimalRacket[\s\S]*activeGreen/, 'feedback poster should expose the selected Gemini template styles');
assert.doesNotMatch(source, /粉蓝笔刷|专业白\(拍网\)|深蓝撞色|波普斜切/, 'feedback poster should remove the rejected poster styles');
assert.match(fnBody('drawFeedbackPoster'), /网球兄弟/, 'feedback poster should use the local brand name');
assert.match(fnBody('drawFeedbackPoster'), /训练反馈/, 'feedback poster should add the training feedback title suffix');
assert.match(fnBody('drawFeedbackPoster'), /用网球向生活发出邀请/, 'feedback poster should show the brand tagline');
assert.match(source, /function posterDisplayDate\(/, 'feedback poster should format lesson date for poster display');
assert.match(source, /function posterTextGroups\(/, 'feedback poster should support highlighted text groups');
assert.match(source, /function measureFeedbackPosterLayout\(/, 'feedback poster should expose a layout measurer for dynamic poster height');
assert.match(fnBody('measureFeedbackPosterLayout'), /posterTextLines[\s\S]*posterBlockHeight[\s\S]*canvasHeight/s, 'feedback poster layout should derive block heights and final canvas height from wrapped text');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /TRAINING REPORT|Coach/, 'feedback poster should remove the old English report and coach footer');
assert.doesNotMatch(fnBody('drawFeedbackPoster'), /canvas\.width=750;canvas\.height=1334;/, 'feedback poster should not hardcode a fixed export height anymore');
assert.match(fnBody('drawFeedbackPoster'), /const layout=measureFeedbackPosterLayout\(ctx,data\);[\s\S]*canvas\.width=750;canvas\.height=layout\.canvasHeight;/s, 'feedback poster should size the canvas from measured content before drawing');
assert.match(fnBody('drawFeedbackPoster'), /layout\.practiced[\s\S]*layout\.knowledge[\s\S]*layout\.nextTraining/s, 'feedback poster should draw the three blocks using measured layout positions');
assert.match(fnBody('openFeedbackPosterModal'), /blueGreenDiagonal/, 'feedback poster modal should default to the first Gemini template');
assert.match(source, /function drawFeedbackPoster\(/, 'feedback poster should draw fixed templates with canvas');
assert.match(source, /function openFeedbackPosterModal\(/, 'feedback poster should expose a modal entry');
assert.match(source, /function downloadFeedbackPoster\(/, 'feedback poster should expose a direct download action');
assert.match(fnBody('openFeedbackPosterModal'), /下载图片[\s\S]*分享图片/, 'feedback poster modal should separate local download from system share');
assert.match(fnBody('shareFeedbackPoster'), /AbortError/, 'cancelled share should not be treated as a generation failure');
assert.match(fnBody('shareFeedbackPoster'), /navigator\.clipboard[\s\S]*ClipboardItem[\s\S]*image\/png/s, 'desktop poster sharing should try writing the PNG into the clipboard before falling back to system share');
assert.match(fnBody('shareFeedbackPoster'), /try\{[\s\S]*navigator\.clipboard\.write[\s\S]*\}catch\(copyErr\)\{[\s\S]*navigator\.share/s, 'poster sharing should fall back to system share when clipboard image copy fails');
assert.match(styles, /::-webkit-scrollbar\{height:3px\}[\s\S]*max-height:58vh/, 'poster preview should fit the modal and use a thin horizontal scrollbar');
assert.match(fnBody('openFeedbackModal'), /生成海报/, 'saved feedback modal should show a poster entry');
assert.match(fnBody('openFeedbackModal'), /trialFieldsHtml/, 'trial conversion fields should be conditional');
assert.match(fnBody('openFeedbackModal'), /练习情况（非必填）/, 'feedback modal should rename knowledge point to practice status');
assert.match(fnBody('openFeedbackModal'), /体验课内部记录/, 'trial-only fields should be framed as internal notes');
assert.match(fnBody('openFeedbackModal'), /1\.0～1\.5[\s\S]*1\.5～2\.0[\s\S]*2\.0～2\.5[\s\S]*2\.5～3\.0[\s\S]*3\.0～3\.5[\s\S]*3\.5～4\.0/, 'trial level options should use the fixed numeric ladder');
assert.doesNotMatch(fnBody('openFeedbackModal'), /知识点（非必填）|体验课转化判断|零基础|初学|有基础|长期打球/, 'feedback modal should remove the old trial copy and level options');
assert.doesNotMatch(fnBody('openFeedbackModal'), /复制给学员/, 'feedback modal should not keep copy action after poster entry exists');
assert.doesNotMatch(fnBody('saveFeedback'), /openFeedbackPosterModal\(/, 'saving feedback should not force coach into poster generation');

console.log('schedule page view tests passed');
