const assert = require('assert');
const { appSource: source } = require('./helpers/read-index-bundle');

assert.match(source, /function renderScheduleStudentPicker/, 'schedule modal should provide a dedicated student picker helper');
assert.match(source, /function scheduleSelectedStudentHomeCampusMeta/, 'schedule modal should derive the selected student home campus');
assert.match(source, /id="sch_homeCampusSummary"/, 'schedule modal should show selected student home campus separately from lesson location');
assert.match(source, /function syncScheduleHomeCampusFromStudents/, 'schedule modal should sync home campus after student selection changes');
assert.match(source, /function scheduleSelectedStudentCoachMeta/, 'schedule modal should derive the selected student primary coach');
assert.match(source, /function syncScheduleProfileFromStudents/, 'schedule modal should sync selected student coach and campus defaults');
assert.match(source, /setCourtDropdownValue\('sch_coach',meta\.coach,meta\.coach\)/, 'schedule modal should default coach from selected student profile');
assert.match(source, /上课校区 \*/, 'schedule own-location field should be labelled as lesson campus, not student home campus');
assert.match(source, /校区内[\s\S]*校区外/, 'schedule location type copy should separate in-campus and off-campus lessons');
assert.match(source, /id="sch_stuSearch"/, 'schedule modal should provide a searchable student input');
assert.match(source, /id="sch_stuPicker"/, 'schedule modal should provide a student library picker');
assert.doesNotMatch(source, /id="sch_stuName"[^>]*placeholder="选班次自动填入"/, 'schedule modal should not use free text student input as the formal selector');
assert.match(source, /function getFilteredStudents\(/, 'student page should centralize filtered student list calculation');
assert.match(source, /function onStudentFilterChange\(\)\{stuPage=1;renderStudents\(\);\}/, 'student filters should reset pagination to first page');
assert.match(source, /oninput="onStudentFilterChange\(\)"/, 'student search should reset pagination before rendering');
assert.match(source, /function renderStudentToolbarFilters\(/, 'student filters should render through the booking-style dropdown helper');
assert.match(source, /stuTypeFilterHost[\s\S]*onStudentFilterChange/, 'student type filter should reset pagination before rendering');
assert.match(source, /stuSourceFilterHost[\s\S]*onStudentFilterChange/, 'student source filter should reset pagination before rendering');
assert.match(source, /stuCoachFilterHost[\s\S]*onStudentFilterChange/, 'student primary coach filter should reset pagination before rendering');
assert.match(source, /function getStudentDuplicateCandidates\(/, 'student save flow should detect possible duplicates before submit');
assert.match(source, /发现可能重复的学员：/, 'student save flow should warn operators about possible duplicates');
assert.match(source, /const d=getFilteredStudents\(\);[\s\S]*a\.download='FlowTennis_学员_'\+today\(\)\+'.csv'/, 'student csv export should use current filtered result set');
assert.match(source, /stuCoachFilterHost/, 'student page should include primary coach filter host');
assert.match(source, /全部负责教练[\s\S]*未分配/, 'student filters should expose responsible coach options');
assert.match(source, /学员总数[\s\S]*今日课时[\s\S]*本周课时[\s\S]*本月课时[\s\S]*本月体验课转化率[\s\S]*待转化/, 'student top stats should use the all-coach workbench metric set');
assert.match(source, /function studentPageStats\(/, 'student page should centralize top stat calculation');
assert.match(source, /pendingConversion:base\.filter\(s=>studentNeedsConversion\(s\)\)\.length/, 'student stats should summarize pending conversion from trial-without-purchase students');
assert.match(source, /function studentStatusMeta\(/, 'student list should compute business status labels');
assert.match(source, /上课中[\s\S]*待转化[\s\S]*沉默30天[\s\S]*仅订场[\s\S]*无班次/, 'student status labels should cover the agreed business states');
assert.match(source, /function studentNoteSummary\(/, 'student list should compute compact ops-style note summary');
assert.match(source, /<table class="tms-table">[\s\S]*<th[^>]*>学员<\/th><th[^>]*>电话<\/th><th[^>]*>类型<\/th><th[^>]*>校区<\/th><th[^>]*>当前班次<\/th><th[^>]*>最近上课<\/th><th[^>]*>累计上课<\/th><th[^>]*>负责教练<\/th><th[^>]*>课包\/课时<\/th><th[^>]*>订场\/会员<\/th><th[^>]*>来源<\/th><th[^>]*>备注<\/th><th[^>]*>操作<\/th>/, 'student table should add cumulative lesson count beside last lesson');
assert.match(source, /function studentCompletedLessonCount\(/, 'student page should expose a cumulative completed lesson helper');
assert.match(source, /studentCompletedLessonCount\(s\)/, 'student list should render cumulative completed lessons');
assert.match(source, /function scheduleLessonUnits\(/, 'lesson stats should use schedule lesson units instead of row counts');
assert.match(source, /function studentPrimaryCoachText\(/, 'student list should render primary coach from the profile field');
assert.match(source, /studentPrimaryCoachText\(s\)/, 'student list coach column should use the profile primary coach');
assert.match(source, /未分配/, 'empty primary coach should display 未分配');
assert.match(source, /const SOURCES=\['转介绍','小红书','大众点评','视频号','抖音','播客','孙老师','其他'\]/, 'student source options should keep the unified ops order');
assert.match(source, /function renderCourtCellText[\s\S]*const muted=!raw\|\|raw==='-'\|\|raw==='—'\|\|raw==='未开卡'/, 'empty list values should always render with the muted dash style');
assert.match(source, /function renderCourtEmptyText[\s\S]*return raw&&raw!=='—'\?raw:'-'/, 'empty values should render with the short dash');
assert.doesNotMatch(source, /<th>最后订场<\/th>/, 'student table should remove last-court as a primary list column in phase 2');
assert.doesNotMatch(source, /<th>关联账户<\/th>/, 'student table should replace account wording with booking membership summary');
assert.match(source, /课包\/课时<\/th><th style="width:120px">订场\/会员/, 'student package and booking columns should be compact');
assert.match(source, /<th style="width:80px">课包\/课时<\/th>/, 'student package lesson column should be 40px narrower');
assert.match(source, /function studentPackageLessonMeta\(/, 'student package lesson summary should expose remaining and total lessons');
assert.match(source, /function studentPackageLessonMiniBar\(/, 'student package lesson column should render the same mini balance bar as booking accounts');
assert.match(source, /studentPackageLessonMiniBar\(s\)/, 'student list should render package lessons through the mini balance bar');
assert.match(source, /\$\{lessonQty\(remaining\)\}\/\$\{lessonQty\(total\)\}/, 'student package lesson text should use remaining over total lesson count without truncating half lessons');
assert.match(source, /student-summary-strong/, 'student rows should visually distinguish non-empty package and booking summaries');
assert.match(source, /function openStudentDetail\(/, 'student list should provide a dedicated view action');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should prioritize view before edit');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openStudentPurchaseModal\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should expose a direct package purchase shortcut between view and edit');
assert.match(source, /function ensureStudentPurchaseDatasets\(/, 'student page should preload purchase datasets before opening package flows');
assert.match(source, /ensureDatasetsByName\(\['purchasesPage','coaches'\]\)/, 'student package entry should reuse the purchases page data bundle and coach list');
assert.match(source, /function studentTeachingInfoHtml\(/, 'student detail should render teaching info block');
assert.match(source, /function studentOpsInfoHtml\(/, 'student detail should render operations info block');
assert.match(source, /function studentConsumptionInfoHtml\(/, 'student detail should render consumption relation block');
assert.match(source, /function studentLessonRecordHtml\(/, 'student detail should expose a dedicated lesson record helper');
assert.match(source, /function studentEntitlementLedgerHtml\(/, 'student detail should provide a dedicated lesson charge history helper');
assert.match(source, /function entitlementLedgerDisplayDate\(/, 'lesson charge history should display the real lesson or month date instead of import time');
assert.match(source, /function historicalImportedLedgerMonthKey\(/, 'lesson charge history should infer monthly import identity from sourceMonth or reason text');
assert.match(source, /reason\.match\(\s*\/\^历史导入\\s\*\(\\d\{1,2\}\)月消课\$\/\s*\)/, 'lesson charge history should fall back to parsing month from reason text when sourceMonth is missing');
assert.match(source, /dedupeEntitlementLedgerForDisplay/, 'lesson charge history should collapse duplicate ledger rows before display');
assert.match(source, /function historicalImportedLessonUnitsForStudent\(/, 'student page should expose a historical imported lesson helper');
assert.match(source, /aggregateHistoricalMonthlyLedgerRows/, 'student consume history should aggregate historical monthly rows before display');
assert.match(source, /studentCompletedLessonCount[\s\S]*historicalImportedLessonUnitsForStudent/, 'student cumulative lessons should include imported lesson consumption');
assert.match(source, /教学信息[\s\S]*运营信息[\s\S]*消费与关联信息/, 'student detail should follow the agreed information hierarchy');
assert.match(source, /上课记录/, 'student detail should provide lesson record history in plain language');
assert.match(source, /已购课包/, 'student detail should present purchased packages in plain language');
assert.match(source, /扣课记录/, 'student detail should expose lesson charge history in the student detail');
assert.match(source, /课包购买记录/, 'student detail should label package purchase records clearly');
assert.match(source, /课包消耗记录/, 'student detail should label package consume records clearly');
assert.match(source, /关联订场账户在「订场\/会员」页面编辑用户时选择「关联学员」/, 'student detail should explain where to link booking accounts');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*studentLinkedDetailHtml\(s\)/, 'student edit modal should not embed linked detail summary anymore');
assert.match(source, /function openStudentModal[\s\S]*姓名 \*[\s\S]*手机号[\s\S]*负责教练[\s\S]*学员类型[\s\S]*来源[\s\S]*活动范围[\s\S]*所在校区[\s\S]*备注/, 'student edit modal should keep base profile fields and expose primary coach');
assert.match(source, /const campusOptions=studentCampusOptions\(\);/, 'student edit modal should build campus options through the shared student helper');
assert.match(source, /function studentCampusOptions\(/, 'student edit modal should expose all loaded campuses through a helper');
assert.match(source, /renderCourtDropdownHtml\('s_primaryCoach'/, 'student edit modal should provide a primary coach selector');
assert.match(source, /const data=\{name,phone,primaryCoach:/, 'student save should submit primary coach');
assert.match(source, /function openStudentModal[\s\S]*setCourtModalFrame\(/, 'student edit modal should reuse the booking-style modal shell');
assert.match(source, /选择课包 \*[\s\S]*主归属教练[\s\S]*支付日期[\s\S]*系统价格[\s\S]*实收金额[\s\S]*支付方式/, 'purchase modal should arrange package, owner, payment date, price and pay method in compact rows');
assert.match(source, /销售归属校区 \*/, 'purchase modal should collect the actual sale campus separately from usable campuses');
assert.match(source, /id="purchaseCreateSaveBtn"[\s\S]*onclick="savePurchase\(\)"/, 'purchase modal save button should expose a stable DOM id for save handler state');
assert.match(source, /id="purchaseEditSaveBtn"[\s\S]*onclick="savePurchaseEdit\('/, 'purchase edit modal save button should expose a stable DOM id for save handler state');
assert.match(source, /document\.getElementById\('purchaseCreateSaveBtn'\)/, 'purchase create save flow should target its real footer button');
assert.match(source, /document\.getElementById\('purchaseEditSaveBtn'\)/, 'purchase edit save flow should target its real footer button');
assert.match(source, /实际成交价与系统价格不一致时必填/, 'purchase modal should require an override reason when final price differs');
assert.match(source, /购买后的学员、课包、归属教练、销售校区不能直接改，请作废后重建/, 'purchase edit modal should warn that ownership fields are no longer directly editable');
assert.match(source, /\['pur_edit_studentId_dropdown','pur_edit_packageId_dropdown','pur_edit_ownerCoach_dropdown','pur_edit_saleCampusId_dropdown'\]/, 'purchase edit modal should lock core ownership dropdowns');
assert.match(source, /tms-readonly-text/, 'student detail long readonly fields should use padded readonly text blocks');
assert.match(source, /purchase-coach-wrap[\s\S]*purchase-notes-row/, 'purchase modal should leave space between allowed coaches and notes');
assert.match(source, /购买日期<\/th><th style="width:120px">学员\/支付<\/th><th style="width:170px">课包\/课程<\/th><th style="width:90px">实收<\/th><th style="width:95px">余额<\/th><th style="width:135px">有效期<\/th><th style="width:80px">状态<\/th><th style="width:95px">归属教练<\/th>/, 'purchase record table should split validity and status into compact ordered columns');

console.log('student page view tests passed');
