const assert = require('assert');
const { appSource: source } = require('./helpers/read-index-bundle');

assert.match(source, /function renderScheduleStudentPicker/, 'schedule modal should provide a dedicated student picker helper');
assert.match(source, /id="sch_stuSearch"/, 'schedule modal should provide a searchable student input');
assert.match(source, /id="sch_stuPicker"/, 'schedule modal should provide a student library picker');
assert.doesNotMatch(source, /id="sch_stuName"[^>]*placeholder="选班次自动填入"/, 'schedule modal should not use free text student input as the formal selector');
assert.match(source, /function getFilteredStudents\(/, 'student page should centralize filtered student list calculation');
assert.match(source, /function onStudentFilterChange\(\)\{stuPage=1;renderStudents\(\);\}/, 'student filters should reset pagination to first page');
assert.match(source, /oninput="onStudentFilterChange\(\)"/, 'student search should reset pagination before rendering');
assert.match(source, /function renderStudentToolbarFilters\(/, 'student filters should render through the booking-style dropdown helper');
assert.match(source, /stuTypeFilterHost[\s\S]*onStudentFilterChange/, 'student type filter should reset pagination before rendering');
assert.match(source, /stuSourceFilterHost[\s\S]*onStudentFilterChange/, 'student source filter should reset pagination before rendering');
assert.match(source, /stuCoachFilterHost[\s\S]*onStudentFilterChange/, 'student primary coach filter should reset pagination before rendering');
assert.match(source, /function getStudentDuplicateCandidates\(/, 'student save flow should detect possible duplicates before submit');
assert.match(source, /发现可能重复的学员：/, 'student save flow should warn operators about possible duplicates');
assert.match(source, /const d=getFilteredStudents\(\);[\s\S]*a\.download='FlowTennis_学员_'\+today\(\)\+'.csv'/, 'student csv export should use current filtered result set');
assert.match(source, /stuCoachFilterHost/, 'student page should include primary coach filter host');
assert.match(source, /全部负责教练[\s\S]*未分配/, 'student filters should expose responsible coach options');
assert.match(source, /const activeCount=base\.filter\(s=>studentStatusMeta\(s\)\.label==='上课中'\)\.length;/, 'student stats should summarize active students');
assert.match(source, /const convertingCount=base\.filter\(s=>studentStatusMeta\(s\)\.label==='待转化'\)\.length;/, 'student stats should summarize converting students');
assert.match(source, /const silentCount=base\.filter\(s=>studentStatusMeta\(s\)\.label==='沉默30天'\)\.length;/, 'student stats should summarize silent students');
assert.match(source, /const relationCount=base\.filter\(s=>studentBookingMembershipSummary\(s\)!=='未关联'\)\.length;/, 'student stats should summarize linked relations');
assert.match(source, /function studentStatusMeta\(/, 'student list should compute business status labels');
assert.match(source, /上课中[\s\S]*待转化[\s\S]*沉默30天[\s\S]*仅订场[\s\S]*无班次/, 'student status labels should cover the agreed business states');
assert.match(source, /function studentNoteSummary\(/, 'student list should compute compact ops-style note summary');
assert.match(source, /<table class="tms-table">[\s\S]*<th[^>]*>学员<\/th><th[^>]*>电话<\/th><th[^>]*>类型<\/th><th[^>]*>校区<\/th><th[^>]*>当前班次<\/th><th[^>]*>最近上课<\/th><th[^>]*>累计上课<\/th><th[^>]*>负责教练<\/th><th[^>]*>课包\/课时<\/th><th[^>]*>订场\/会员<\/th><th[^>]*>来源<\/th><th[^>]*>备注<\/th><th[^>]*>操作<\/th>/, 'student table should add cumulative lesson count beside last lesson');
assert.match(source, /function studentCompletedLessonCount\(/, 'student page should expose a cumulative completed lesson helper');
assert.match(source, /studentCompletedLessonCount\(s\)/, 'student list should render cumulative completed lessons');
assert.match(source, /function studentPrimaryCoachText\(/, 'student list should render primary coach from the profile field');
assert.match(source, /studentPrimaryCoachText\(s\)/, 'student list coach column should use the profile primary coach');
assert.match(source, /未分配/, 'empty primary coach should display 未分配');
assert.match(source, /const SOURCES=\['转介绍','小红书','大众点评','视频号','抖音','播客','孙老师','其他'\]/, 'student source options should keep the unified ops order');
assert.match(source, /function renderCourtCellText[\s\S]*const muted=!raw\|\|raw==='-'\|\|raw==='—'\|\|raw==='未开卡'/, 'empty list values should always render with the muted dash style');
assert.doesNotMatch(source, /<th>最后订场<\/th>/, 'student table should remove last-court as a primary list column in phase 2');
assert.doesNotMatch(source, /<th>关联账户<\/th>/, 'student table should replace account wording with booking membership summary');
assert.match(source, /function openStudentDetail\(/, 'student list should provide a dedicated view action');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should prioritize view before edit');
assert.match(source, /openStudentDetail\('[^']+'\)[\s\S]*openPurchaseModal\('[^']+'\)[\s\S]*openStudentModal\('[^']+'\)/, 'student row should expose a direct package purchase shortcut between view and edit');
assert.match(source, /function studentTeachingInfoHtml\(/, 'student detail should render teaching info block');
assert.match(source, /function studentOpsInfoHtml\(/, 'student detail should render operations info block');
assert.match(source, /function studentConsumptionInfoHtml\(/, 'student detail should render consumption relation block');
assert.match(source, /function studentLessonRecordHtml\(/, 'student detail should expose a dedicated lesson record helper');
assert.match(source, /function studentEntitlementLedgerHtml\(/, 'student detail should provide a dedicated lesson charge history helper');
assert.match(source, /教学信息[\s\S]*运营信息[\s\S]*消费与关联信息/, 'student detail should follow the agreed information hierarchy');
assert.match(source, /上课记录/, 'student detail should provide lesson record history in plain language');
assert.match(source, /已购课包/, 'student detail should present purchased packages in plain language');
assert.match(source, /扣课记录/, 'student detail should expose lesson charge history in the student detail');
assert.doesNotMatch(source, /function openStudentModal[\s\S]*studentLinkedDetailHtml\(s\)/, 'student edit modal should not embed linked detail summary anymore');
assert.match(source, /function openStudentModal[\s\S]*姓名 \*[\s\S]*手机号[\s\S]*负责教练[\s\S]*学员类型[\s\S]*来源[\s\S]*活动范围[\s\S]*所在校区[\s\S]*备注/, 'student edit modal should keep base profile fields and expose primary coach');
assert.match(source, /renderCourtDropdownHtml\('s_primaryCoach'/, 'student edit modal should provide a primary coach selector');
assert.match(source, /const data=\{name,phone,primaryCoach:/, 'student save should submit primary coach');
assert.match(source, /function openStudentModal[\s\S]*setCourtModalFrame\(/, 'student edit modal should reuse the booking-style modal shell');

console.log('student page view tests passed');
